// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vsoc_top.h for the primary calling header

#include "Vsoc_top__pch.h"

// Parameter definitions for Vsoc_top___024root
constexpr CData/*0:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__FALL_THROUGH;
constexpr CData/*1:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__MTVEC_MODE;
constexpr CData/*1:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__MXL;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_uart_0__DOT__ADDR_CPB;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_uart_0__DOT__ADDR_STP;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_uart_0__DOT__ADDR_RDR;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_uart_0__DOT__ADDR_TDR;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_uart_0__DOT__ADDR_CFG;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_gpio__DOT__ADDR_IDR;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_gpio__DOT__ADDR_ODR;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_timer__DOT__ADDR_PRE;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_timer__DOT__ADDR_ARE;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_timer__DOT__ADDR_CLR;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_timer__DOT__ADDR_ENA;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_timer__DOT__ADDR_MOD;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_timer__DOT__ADDR_CNT;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_timer__DOT__ADDR_EVN;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_timer__DOT__ADDR_EVC;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_qspi__DOT__ADDR_CCR;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_qspi__DOT__ADDR_ADR;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_qspi__DOT__ADDR_DR;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_qspi__DOT__ADDR_STA;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_qspi__DOT__ADDR_FCR;
constexpr CData/*7:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__INPUT_ZP;
constexpr CData/*7:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__CONV_OUT_ZP;
constexpr CData/*7:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__FC_OUT_ZP;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__CSR_CTRL;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__CSR_STATUS;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__CSR_DATA_ADDR;
constexpr CData/*4:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__CSR_OUT_ADDR;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__BOOT_ADDR;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__INSTR_SRAM_BYTES;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__DATA_SRAM_BYTES;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__COREV_PULP;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__COREV_CLUSTER;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__FPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__FPU_ADDMUL_LAT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__FPU_OTHERS_LAT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__ZFINX;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__NUM_MHPMCOUNTERS;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__COREV_PULP;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__COREV_CLUSTER;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__FPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__FPU_ADDMUL_LAT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__FPU_OTHERS_LAT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__ZFINX;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__NUM_MHPMCOUNTERS;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__PULP_SECURE;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__N_PMP_ENTRIES;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__USE_PMP;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__A_EXTENSION;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__DEBUG_TRIGGER_EN;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__PULP_OBI;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__N_HWLP;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__APU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__sleep_unit_i__DOT__COREV_CLUSTER;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__COREV_PULP;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__PULP_OBI;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__PULP_SECURE;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__FPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__ZFINX;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__prefetch_buffer_i__DOT__PULP_OBI;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__prefetch_buffer_i__DOT__COREV_PULP;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__prefetch_buffer_i__DOT__FIFO_DEPTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__prefetch_buffer_i__DOT__FIFO_ADDR_DEPTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__prefetch_buffer_i__DOT__prefetch_controller_i__DOT__PULP_OBI;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__prefetch_buffer_i__DOT__prefetch_controller_i__DOT__COREV_PULP;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__prefetch_buffer_i__DOT__prefetch_controller_i__DOT__DEPTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__prefetch_buffer_i__DOT__prefetch_controller_i__DOT__FIFO_ADDR_DEPTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__DEPTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__ADDR_DEPTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__FIFO_DEPTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__prefetch_buffer_i__DOT__instruction_obi_i__DOT__TRANS_STABLE;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__FPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__ZFINX;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__COREV_PULP;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__COREV_CLUSTER;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__N_HWLP;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__N_HWLP_BITS;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__PULP_SECURE;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__USE_PMP;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__A_EXTENSION;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__APU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__FPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__FPU_ADDMUL_LAT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__FPU_OTHERS_LAT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__ZFINX;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__APU_NARGS_CPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__APU_WOP_CPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__APU_NDSFLAGS_CPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__APU_NUSFLAGS_CPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__DEBUG_TRIGGER_EN;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__REG_S1_MSB;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__REG_S1_LSB;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__REG_S2_MSB;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__REG_S2_LSB;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__REG_S4_MSB;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__REG_S4_LSB;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__REG_D_MSB;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__REG_D_LSB;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__register_file_i__DOT__ADDR_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__register_file_i__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__register_file_i__DOT__FPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__register_file_i__DOT__ZFINX;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__register_file_i__DOT__NUM_WORDS;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__register_file_i__DOT__NUM_FP_WORDS;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__register_file_i__DOT__NUM_TOT_WORDS;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__decoder_i__DOT__COREV_PULP;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__decoder_i__DOT__COREV_CLUSTER;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__decoder_i__DOT__A_EXTENSION;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__decoder_i__DOT__FPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__decoder_i__DOT__FPU_ADDMUL_LAT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__decoder_i__DOT__FPU_OTHERS_LAT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__decoder_i__DOT__ZFINX;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__decoder_i__DOT__PULP_SECURE;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__decoder_i__DOT__USE_PMP;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__decoder_i__DOT__APU_WOP_CPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__decoder_i__DOT__DEBUG_TRIGGER_EN;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__controller_i__DOT__COREV_CLUSTER;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__controller_i__DOT__COREV_PULP;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__controller_i__DOT__FPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__id_stage_i__DOT__int_controller_i__DOT__PULP_SECURE;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__ex_stage_i__DOT__COREV_PULP;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__ex_stage_i__DOT__FPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__ex_stage_i__DOT__APU_NARGS_CPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__ex_stage_i__DOT__APU_WOP_CPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__ex_stage_i__DOT__APU_NDSFLAGS_CPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__ex_stage_i__DOT__APU_NUSFLAGS_CPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__ex_stage_i__DOT__alu_i__DOT__ff_one_i__DOT__LEN;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__ex_stage_i__DOT__alu_i__DOT__ff_one_i__DOT__NUM_LEVELS;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__ex_stage_i__DOT__alu_i__DOT__alu_div_i__DOT__C_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__ex_stage_i__DOT__alu_i__DOT__alu_div_i__DOT__C_LOG_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__load_store_unit_i__DOT__PULP_OBI;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__load_store_unit_i__DOT__DEPTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__load_store_unit_i__DOT__data_obi_i__DOT__TRANS_STABLE;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__N_HWLP;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__APU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__A_EXTENSION;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__FPU;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__ZFINX;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__PULP_SECURE;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__USE_PMP;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__N_PMP_ENTRIES;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__NUM_MHPMCOUNTERS;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__COREV_PULP;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__COREV_CLUSTER;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__DEBUG_TRIGGER_EN;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__NUM_HPM_EVENTS;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__MAX_N_PMP_ENTRIES;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__MAX_N_PMP_CFG;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__N_PMP_CFG;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__MSTATUS_UIE_BIT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__MSTATUS_SIE_BIT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__MSTATUS_MIE_BIT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__MSTATUS_UPIE_BIT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__MSTATUS_SPIE_BIT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__MSTATUS_MPIE_BIT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__MSTATUS_SPP_BIT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__MSTATUS_MPP_BIT_LOW;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__MSTATUS_MPP_BIT_HIGH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__MSTATUS_FS_BIT_LOW;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__MSTATUS_FS_BIT_HIGH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__MSTATUS_MPRV_BIT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__MSTATUS_SD_BIT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__MISA_VALUE;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_cpu__DOT__core_i__DOT__cs_registers_i__DOT__PULP_PERF_COUNTERS;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_obi_axi_instr__DOT__AXI_ID;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_obi_axi_data__DOT__AXI_ID;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_uart_0__DOT__i_uart_tx__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_uart_0__DOT__i_uart_rx__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_qspi__DOT__FIFO_DEPTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_qspi__DOT__FIFO_AW;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__CONV_SHIFT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__FC_SHIFT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__M_FC_Q31;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__SHIFT_FC;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__AI_SRAM_BASE;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__CONV_OUT_OFF;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__CONV_W_OFF;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__CONV_BIAS_OFF;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__FC_W_OFF;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__FC_BIAS_OFF;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__DEFAULT_OUT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__INPUT_H;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__INPUT_W;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__KERNEL_H;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__KERNEL_W;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__NUM_FILTERS;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__PAD_TOP;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__PAD_LEFT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__STRIDE;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__CONV_OUT_H;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__CONV_OUT_W;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__FC_IN;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__FC_OUT;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__INPUT_WORDS;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__CONV_W_WORDS;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__CONV_OUT_WORDS;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_boot_rom__DOT__AXI_ID_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_boot_rom__DOT__AXI_ADDR_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_boot_rom__DOT__AXI_DATA_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_boot_rom__DOT__SRAM_BYTES;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_boot_rom__DOT__SRAM_WORDS;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_boot_rom__DOT__ADDR_LSB;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_boot_rom__DOT__WORD_IDX_W;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_boot_rom__DOT__ADDR_MSB;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_instr_sram__DOT__AXI_ID_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_instr_sram__DOT__AXI_ADDR_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_instr_sram__DOT__AXI_DATA_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_instr_sram__DOT__SRAM_BYTES;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_instr_sram__DOT__SRAM_WORDS;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_instr_sram__DOT__ADDR_LSB;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_instr_sram__DOT__WORD_IDX_W;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_instr_sram__DOT__ADDR_MSB;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_data_sram__DOT__AXI_ID_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_data_sram__DOT__AXI_ADDR_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_data_sram__DOT__AXI_DATA_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_data_sram__DOT__SRAM_BYTES;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_data_sram__DOT__SRAM_WORDS;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_data_sram__DOT__ADDR_LSB;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_data_sram__DOT__WORD_IDX_W;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_data_sram__DOT__ADDR_MSB;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_sram__DOT__AXI_ID_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_sram__DOT__AXI_ADDR_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_sram__DOT__AXI_DATA_WIDTH;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_sram__DOT__SRAM_BYTES;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_sram__DOT__SRAM_WORDS;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_sram__DOT__ADDR_LSB;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_sram__DOT__WORD_IDX_W;
constexpr IData/*31:0*/ Vsoc_top___024root::soc_top__DOT__i_ai_sram__DOT__ADDR_MSB;
constexpr VlUnpacked<IData/*31:0*/, 8> Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__M_CONV_Q31;
constexpr VlUnpacked<IData/*31:0*/, 8> Vsoc_top___024root::soc_top__DOT__i_ai_accel__DOT__SHIFT_CONV;
const std::string Vsoc_top___024root::soc_top__DOT__i_boot_rom__DOT__INIT_FILE = "bootrom.hex"s;
const std::string Vsoc_top___024root::soc_top__DOT__i_instr_sram__DOT__INIT_FILE = "firmware.hex"s;
const std::string Vsoc_top___024root::soc_top__DOT__i_data_sram__DOT__INIT_FILE = "data_mem.hex"s;
const std::string Vsoc_top___024root::soc_top__DOT__i_ai_sram__DOT__INIT_FILE = "ai_sram_init.hex"s;
const std::string Vsoc_top___024root::soc_top__DOT__i_protocol_checkers__DOT__i_chk_periph__DOT__INTF_NAME = "PERIPH_BUS"s;
const std::string Vsoc_top___024root::soc_top__DOT__i_protocol_checkers__DOT__i_chk_uart__DOT__INTF_NAME = "UART_0"s;
const std::string Vsoc_top___024root::soc_top__DOT__i_protocol_checkers__DOT__i_chk_gpio__DOT__INTF_NAME = "GPIO"s;
const std::string Vsoc_top___024root::soc_top__DOT__i_protocol_checkers__DOT__i_chk_timer__DOT__INTF_NAME = "TIMER"s;
const std::string Vsoc_top___024root::soc_top__DOT__i_protocol_checkers__DOT__i_chk_qspi__DOT__INTF_NAME = "QSPI"s;


void Vsoc_top___024root___ctor_var_reset(Vsoc_top___024root* vlSelf);

Vsoc_top___024root::Vsoc_top___024root(Vsoc_top__Syms* symsp, const char* namep)
 {
    vlSymsp = symsp;
    vlNamep = strdup(namep);
    // Reset structure values
    Vsoc_top___024root___ctor_var_reset(this);
}

void Vsoc_top___024root::__Vconfigure(bool first) {
    (void)first;  // Prevent unused variable warning
}

Vsoc_top___024root::~Vsoc_top___024root() {
    VL_DO_DANGLING(std::free(const_cast<char*>(vlNamep)), vlNamep);
}
