// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vuart_stp_tb.h for the primary calling header

#ifndef VERILATED_VUART_STP_TB___024ROOT_H_
#define VERILATED_VUART_STP_TB___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vuart_stp_tb__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vuart_stp_tb___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ uart_stp_tb__DOT__clk;
        CData/*0:0*/ uart_stp_tb__DOT__rst_n;
        CData/*0:0*/ uart_stp_tb__DOT__awvalid;
        CData/*0:0*/ uart_stp_tb__DOT__awready;
        CData/*0:0*/ uart_stp_tb__DOT__wvalid;
        CData/*0:0*/ uart_stp_tb__DOT__wready;
        CData/*0:0*/ uart_stp_tb__DOT__bvalid;
        CData/*0:0*/ uart_stp_tb__DOT__arvalid;
        CData/*0:0*/ uart_stp_tb__DOT__arready;
        CData/*0:0*/ uart_stp_tb__DOT__rvalid;
        CData/*0:0*/ uart_stp_tb__DOT__txd_q;
        CData/*1:0*/ uart_stp_tb__DOT__i_dut__DOT__uart_stp;
        CData/*7:0*/ uart_stp_tb__DOT__i_dut__DOT__uart_rdr;
        CData/*7:0*/ uart_stp_tb__DOT__i_dut__DOT__uart_tdr;
        CData/*0:0*/ uart_stp_tb__DOT__i_dut__DOT__cfg_tx_en;
        CData/*0:0*/ uart_stp_tb__DOT__i_dut__DOT__cfg_rx_done;
        CData/*0:0*/ uart_stp_tb__DOT__i_dut__DOT__cfg_tx_done;
        CData/*0:0*/ uart_stp_tb__DOT__i_dut__DOT__prev_tx_busy;
        CData/*0:0*/ uart_stp_tb__DOT__i_dut__DOT__stp_extending;
        CData/*0:0*/ uart_stp_tb__DOT__i_dut__DOT__tx_pending;
        CData/*0:0*/ uart_stp_tb__DOT__i_dut__DOT__tx_pending_fire;
        CData/*0:0*/ uart_stp_tb__DOT__i_dut__DOT__tx_done_set;
        CData/*0:0*/ uart_stp_tb__DOT__i_dut__DOT__stp_ext_load;
        CData/*0:0*/ uart_stp_tb__DOT__i_dut__DOT__stp_hold;
        CData/*0:0*/ uart_stp_tb__DOT__i_dut__DOT__wr_cfg_hit;
        CData/*0:0*/ uart_stp_tb__DOT__i_dut__DOT__wr_tdr_hit;
        CData/*0:0*/ uart_stp_tb__DOT__i_dut__DOT__aw_en;
        CData/*4:0*/ uart_stp_tb__DOT__i_dut__DOT__write_addr;
        CData/*0:0*/ uart_stp_tb__DOT__i_dut__DOT__i_uart_tx__DOT__s_axis_tready_reg;
        CData/*0:0*/ uart_stp_tb__DOT__i_dut__DOT__i_uart_tx__DOT__txd_reg;
        CData/*0:0*/ uart_stp_tb__DOT__i_dut__DOT__i_uart_tx__DOT__busy_reg;
        CData/*3:0*/ uart_stp_tb__DOT__i_dut__DOT__i_uart_tx__DOT__bit_cnt;
        CData/*7:0*/ uart_stp_tb__DOT__i_dut__DOT__i_uart_rx__DOT__m_axis_tdata_reg;
        CData/*0:0*/ uart_stp_tb__DOT__i_dut__DOT__i_uart_rx__DOT__m_axis_tvalid_reg;
        CData/*0:0*/ uart_stp_tb__DOT__i_dut__DOT__i_uart_rx__DOT__rxd_reg;
        CData/*7:0*/ uart_stp_tb__DOT__i_dut__DOT__i_uart_rx__DOT__data_reg;
        CData/*3:0*/ uart_stp_tb__DOT__i_dut__DOT__i_uart_rx__DOT__bit_cnt;
        CData/*0:0*/ __Vdly__uart_stp_tb__DOT__awready;
        CData/*0:0*/ __Vdly__uart_stp_tb__DOT__wready;
        CData/*4:0*/ __Vdly__uart_stp_tb__DOT__i_dut__DOT__write_addr;
        CData/*0:0*/ __Vdly__uart_stp_tb__DOT__bvalid;
        CData/*0:0*/ __Vdly__uart_stp_tb__DOT__i_dut__DOT__tx_pending_fire;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v0;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v0;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v0;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v0;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v1;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v1;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v1;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v1;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v2;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v2;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v3;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v3;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v2;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v2;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v4;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v4;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v5;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v5;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__araddr__v0;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__arvalid__v0;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__arvalid__v1;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v3;
    };
    struct {
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v3;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v6;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v6;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v7;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v7;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v4;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v4;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v8;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v8;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v9;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v9;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__araddr__v1;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__arvalid__v2;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__arvalid__v3;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v5;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v5;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v10;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v10;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v11;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v11;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v6;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v6;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v12;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v12;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v13;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v13;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v7;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v7;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v14;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v14;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v15;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v15;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__araddr__v2;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__arvalid__v4;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__arvalid__v5;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v8;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v8;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v16;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v16;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v17;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v17;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v9;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v9;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v18;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v18;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v19;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v19;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__araddr__v3;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__arvalid__v6;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__arvalid__v7;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v10;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v10;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v20;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v20;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v21;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v21;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v11;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v11;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v22;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v22;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v23;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v23;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v12;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v12;
    };
    struct {
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v24;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v24;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v25;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v25;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__araddr__v4;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__arvalid__v8;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__arvalid__v9;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v13;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v13;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v26;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v26;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v27;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v27;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v14;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v14;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v28;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v28;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v29;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v29;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__araddr__v5;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__arvalid__v10;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__arvalid__v11;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v15;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v15;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v30;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v30;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v31;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v31;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v16;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v16;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v32;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v32;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v33;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v33;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v17;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v17;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v34;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v34;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v35;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v35;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__araddr__v6;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__arvalid__v12;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__arvalid__v13;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v18;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v18;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v36;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v36;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v37;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v37;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v19;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v19;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v38;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v38;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v39;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v39;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__araddr__v7;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__arvalid__v14;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__arvalid__v15;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v20;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v20;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v40;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v40;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v41;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v41;
    };
    struct {
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v21;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v21;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v42;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v42;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v43;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v43;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v22;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v22;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v44;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v44;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v45;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v45;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awaddr__v23;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wdata__v23;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v46;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v46;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__awvalid__v47;
        CData/*0:0*/ __VdlySet__uart_stp_tb__DOT__wvalid__v47;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__uart_stp_tb__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__uart_stp_tb__DOT__rst_n__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VinactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        SData/*8:0*/ uart_stp_tb__DOT__i_dut__DOT__i_uart_tx__DOT__data_reg;
        IData/*31:0*/ uart_stp_tb__DOT__awaddr;
        IData/*31:0*/ uart_stp_tb__DOT__wdata;
        IData/*31:0*/ uart_stp_tb__DOT__araddr;
        IData/*31:0*/ uart_stp_tb__DOT__rdata;
        IData/*31:0*/ uart_stp_tb__DOT__cyc;
        IData/*31:0*/ uart_stp_tb__DOT__start_n;
        IData/*31:0*/ uart_stp_tb__DOT__frame_guard;
        IData/*31:0*/ uart_stp_tb__DOT__i_dut__DOT__uart_cpb;
        IData/*19:0*/ uart_stp_tb__DOT__i_dut__DOT__stp_ext_cnt;
        IData/*31:0*/ uart_stp_tb__DOT__i_dut__DOT__wr_cfg_data;
        IData/*18:0*/ uart_stp_tb__DOT__i_dut__DOT__i_uart_tx__DOT__prescale_reg;
        IData/*18:0*/ uart_stp_tb__DOT__i_dut__DOT__i_uart_rx__DOT__prescale_reg;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v0;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v0;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v1;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v1;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v2;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v2;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__araddr__v0;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v3;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v3;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v4;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v4;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__araddr__v1;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v5;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v5;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v6;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v6;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v7;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v7;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__araddr__v2;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v8;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v8;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v9;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v9;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__araddr__v3;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v10;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v10;
    };
    struct {
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v11;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v11;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v12;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v12;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__araddr__v4;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v13;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v13;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v14;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v14;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__araddr__v5;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v15;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v15;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v16;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v16;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v17;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v17;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__araddr__v6;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v18;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v18;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v19;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v19;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__araddr__v7;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v20;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v20;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v21;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v21;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v22;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v22;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__awaddr__v23;
        IData/*31:0*/ __VdlyVal__uart_stp_tb__DOT__wdata__v23;
        IData/*31:0*/ __VactIterCount;
        IData/*31:0*/ __VinactIterCount;
        IData/*31:0*/ __Vi;
        VlUnpacked<IData/*31:0*/, 16> uart_stp_tb__DOT__start_cyc;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggeredAcc;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_hfb054935__0;

    // INTERNAL VARIABLES
    Vuart_stp_tb__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vuart_stp_tb___024root(Vuart_stp_tb__Syms* symsp, const char* namep);
    ~Vuart_stp_tb___024root();
    VL_UNCOPYABLE(Vuart_stp_tb___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
