# SPDX-FileCopyrightText: 2026 BLogic Mikroelektronik - Berk Muammer Kuzu and Berkin Demircan
# SPDX-License-Identifier: GPL-3.0-only
# Licensed under the GNU General Public License version 3 only.
# See the LICENSE file in the repository root for the full license text.
#
# Test catalogue: what each test proves, what it checks, which files it uses and
# which registers it touches. scripts/test_report.py prints the matching entry
# after every run and writes it into the test's report.txt; docs/TESTS.md is
# generated from this file (python3 scripts/test_report.py --markdown).
#
# FW: firmware tests (key = firmware file name without .c), run on the SoC model.
# TB: make targets that run a testbench or a script (key = make target).

FW = {
    "uart_hello": {
        "title": "UART_0 transmit (Hello World)",
        "purpose": "Proves that the core boots from the instruction SRAM, executes C code and transmits a string through UART_0 at the programmed clocks-per-bit value. In the regression it is run at three baud rates, which shows that the CPB register sets the bit timing.",
        "checks": [
            'UART_0 output must contain "Hello World from BLogic MCU!\\n" (compared by the simulator; result=PASS in result.log)',
            "make regression builds and runs it three times with matching firmware and simulator CPB values: 434 (115200 baud), 50 (about 1 Mbps) and 5208 (9600 baud); each run must report result=PASS",
            "In make regression, any 'PROTOCOL VIOLATION' line from the AXI/AXI-Lite protocol checkers in the simulation output fails the run",
        ],
        "sources": ["sw/tests/uart_hello.c", "sw/drivers/blogic_mcu.h", "sw/common/crt0.S", "sw/common/link.ld", "verif/tb/sim_main.cpp", "scripts/run_regression.sh"],
        "dut": ["rtl/peripherals/uart_axil.sv", "rtl/peripherals/uart_tx.v", "rtl/soc_top.sv", "rtl/bus/soc_axi_interconnect.sv", "rtl/bus/axi4_to_axilite_bridge.sv", "rtl/bus/periph_decoder.sv", "rtl/core/cv32e40p/rtl/axi_sram_wrapper.sv"],
        "registers": ["UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "make sim (default FW_SRC); make regression (tests UART_TX_115200, UART_TX_1M, UART_TX_9600); make coverage. It is also the resident program for make jtag-sim and make jtag-openocd-build, where the JTAG testbench decides pass or fail.",
    },
    "uart_loopback": {
        "title": "UART_0 single-byte receive (loopback)",
        "purpose": "Proves that a byte arriving on the UART_0 RX line is received, raises RX_READY and can be read from RDR. It transmits 'B' and expects the same byte back on RX.",
        "checks": [
            "The byte read from UART0.RDR must equal the transmitted 'B'; the firmware then prints \"LOOPBACK SUCCESS\\n\", otherwise \"LOOPBACK FAILED\\n\"",
            "In make uart-rx-bisect the TX-to-RX loopback is off: the simulator injects the byte 'B' (or the file given in BISECT_FRAME) 5000 cycles after the MCU has printed 'B', and the golden file requires UART_0 output to contain \"LOOPBACK SUCCESS\" (compared by the simulator, MAX_CYCLES 600000)",
            "The target prints the result= and uart_rx_ lines of result.log and the UART_0 output; a simulator FAIL makes the make call fail",
        ],
        "sources": ["sw/tests/uart_loopback.c", "sw/drivers/blogic_mcu.h", "verif/tb/sim_main.cpp"],
        "dut": ["rtl/peripherals/uart_axil.sv", "rtl/peripherals/uart_rx.v", "rtl/peripherals/uart_tx.v"],
        "registers": ["UART0.CPB", "UART0.TDR", "UART0.CFG", "UART0.RDR"],
        "run": "make uart-rx-bisect (a diagnostic target, not part of test-all). With the simulator's default TX-to-RX wire loopback it can also be run as make sim FW_SRC=sw/tests/uart_loopback.c SIM_PLUSARGS=+TEST=LOOPBACK.",
    },
    "uart_baud_sweep": {
        "title": "UART_0 baud-rate sweep (115200, 1 Mbps, 9600)",
        "purpose": "Proves that UART_0 can be reprogrammed at run time to three different baud rates in one run and transmits correctly at each of them.",
        "checks": [
            'In +SWEEP=434,50,5208 mode the simulator looks for "BAUD-OK\\n" three times in order, switching its receiver to the next CPB (434, then 50, then 5208) after each match; result=PASS only if all three phases are found',
            "The firmware CPB values are set at compile time with -DSWEEP_CPB0=434 -DSWEEP_CPB1=50 -DSWEEP_CPB2=5208",
            "make uart-baud additionally requires a line starting with result=PASS in logs/sim/uart_baud_sweep/result.log",
        ],
        "sources": ["sw/tests/uart_baud_sweep.c", "verif/tb/sim_main.cpp"],
        "dut": ["rtl/peripherals/uart_axil.sv", "rtl/peripherals/uart_tx.v"],
        "registers": ["UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "make uart-baud (part of make test-all); make coverage (same CFLAGS and plusargs)",
    },
    "minimal_test": {
        "title": "Spike lockstep, minimal program",
        "purpose": "Proves that the RTL core retires the same sequence of program counters as the Spike reference ISS for a minimal add-and-store program. It has no MMIO accesses and produces no UART output.",
        "checks": [
            "Spike is run on the same ELF with commit logging enabled (memory at 0x10000 and 0x20000, 8 KB each) and stopped after one second",
            "verif/spike/compare_traces.py compares the RTL trace (RTL_PC lines of rtl_trace.log, written by sim_main.cpp at each retired instruction) with the Spike commits in [0x10000, 0x20000); every PC in the common length must match, otherwise FAIL",
            "Only PCs are compared, not register or memory values; the stored test_result value (0xCAFEBABE) is not checked",
            "The simulator's own UART golden result is ignored for this program (it prints nothing)",
        ],
        "sources": ["sw/tests/minimal_test.c", "verif/spike/compare_traces.py", "verif/tb/sim_main.cpp", "scripts/run_regression.sh"],
        "dut": ["rtl/core/cv32e40p/rtl/cv32e40p_if_stage.sv", "rtl/core/cv32e40p/rtl/cv32e40p_id_stage.sv", "rtl/core/cv32e40p/rtl/cv32e40p_ex_stage.sv", "rtl/core/cv32e40p/rtl/cv32e40p_load_store_unit.sv", "rtl/core/cv32e40p/rtl/axi_sram_wrapper.sv", "rtl/bus/obi_to_axi.sv"],
        "registers": [],
        "run": "make regression (test lockstep_minimal; needs Spike)",
    },
    "lockstep_deep": {
        "title": "Spike lockstep, deep RV32IM program",
        "purpose": "Proves that the RTL core follows Spike instruction by instruction over a deterministic program of about 3000 instructions that mixes multiplication, real unsigned division, loads, stores and data-dependent branches, with no MMIO.",
        "checks": [
            "Spike is run on the same ELF with commit logging enabled and stopped after one second",
            "verif/spike/compare_traces.py compares the RTL retired-PC trace with the Spike commits in [0x10000, 0x20000); every PC in the common length must match, otherwise FAIL",
            "Only the PC sequence is compared; the final value written to result is not checked",
            "The simulator's own UART golden result is ignored for this program (it prints nothing)",
        ],
        "sources": ["sw/tests/lockstep_deep.c", "verif/spike/compare_traces.py", "verif/tb/sim_main.cpp", "scripts/run_regression.sh"],
        "dut": ["rtl/core/cv32e40p/rtl/cv32e40p_id_stage.sv", "rtl/core/cv32e40p/rtl/cv32e40p_ex_stage.sv", "rtl/core/cv32e40p/rtl/cv32e40p_mult.sv", "rtl/core/cv32e40p/rtl/cv32e40p_alu_div.sv", "rtl/core/cv32e40p/rtl/cv32e40p_load_store_unit.sv", "rtl/core/cv32e40p/rtl/axi_sram_wrapper.sv"],
        "registers": [],
        "run": "make regression (test lockstep_deep; needs Spike)",
    },
    "qspi_test": {
        "title": "QSPI single-byte flash read",
        "purpose": "Proves that the CPU can start a x1 READ (0x03) command on the QSPI master, wait for completion and read the received byte back from the data register.",
        "checks": [
            "Reads one byte from flash address 0 (CCR: instruction 0x03, x1 data mode, 1 byte) and polls STA busy until it clears",
            "The byte must be 0xAA, the value returned by the fixed QSPI responder in verif/tb/sim_main.cpp (0xAA on IO1 after the first 32 SCLK edges, independent of the command); only then is the golden string printed, otherwise \"QSPI READ ERROR!\"",
            'UART_0 output must contain "Hello World from BLogic MCU!\\n" (compared by the simulator)',
            "In make regression, any 'PROTOCOL VIOLATION' line from the protocol checkers fails the run",
        ],
        "sources": ["sw/tests/qspi_test.c", "sw/drivers/qspi.h", "verif/tb/sim_main.cpp", "scripts/run_regression.sh"],
        "dut": ["rtl/peripherals/qspi_master_axil.sv"],
        "registers": ["QSPI.ADR", "QSPI.CCR", "QSPI.STA", "QSPI.DR", "UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "make regression (test QSPI_Flash); make coverage",
    },
    "ai_micro_speech_test": {
        "title": "AI accelerator inference from C (polling)",
        "purpose": "Proves that the CPU can configure the AI accelerator CSRs, start one keyword-spotting inference on the preloaded recorded 'yes' features (yes_real), detect completion by polling STATUS and read the class both from STATUS and from the result word written to AI SRAM.",
        "checks": [
            "OUT_ADDR is written and read back; a sentinel 0xDEADBEEF is written to the result location (0x35A58) before START so a stale value cannot pass",
            "STATUS.DONE must be set within 500000 polls; on timeout a FAIL line is printed and the golden string is not",
            "The argmax field of STATUS (bits 7:4) must be 2 ('yes') and the low nibble of the result word at OUT_ADDR must also be 2",
            'Only when both match does the firmware print "[AI] PASS" and "Hello World from BLogic MCU!\\n"; the simulator compares the golden string, and make soc-ai also requires result=PASS in result.log',
            "Debug values (STATUS before start, conv_out[0..3], memory words around the result) are printed but not checked",
        ],
        "sources": ["sw/tests/ai_micro_speech_test.c", "sw/ai_model/golden_vectors/ai_sram_init.hex", "sw/ai_model/generate_ai_sram_init.py"],
        "dut": ["rtl/ai_accelerator/ai_accelerator.sv", "rtl/ai_accelerator/ai_sram_arbiter.sv", "rtl/core/cv32e40p/rtl/axi_sram_wrapper.sv"],
        "registers": ["AI.STATUS", "AI.DATA_ADDR", "AI.OUT_ADDR", "AI.CTRL", "UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "make soc-ai (part of make test-all); make coverage",
    },
    "ai_irq_test": {
        "title": "AI accelerator completion interrupt (irq 17, ISR)",
        "purpose": "Proves that the accelerator's level interrupt on fast interrupt line 17 reaches the core, wakes it from WFI, enters the ISR through the vector table, and that clearing DONE in the ISR removes the interrupt source so the ISR runs exactly once.",
        "checks": [
            "Enables mie[17] and mstatus.MIE, writes CTRL.START and waits in a WFI loop (up to 2000000 wake-ups) for the ISR flag",
            "The ISR must run; otherwise a timeout FAIL line is printed",
            "The ISR must have run exactly once (a second call indicates that the clear path did not drop the level interrupt)",
            "The argmax field of the STATUS value read in the ISR must be 2 ('yes')",
            "STATUS.DONE must read 0 after the ISR",
            'Only if all checks pass does the firmware print "[AI-IRQ] PASS" and "Hello World from BLogic MCU!\\n" (compared by the simulator); make soc-ai-irq also requires result=PASS in result.log',
        ],
        "sources": ["sw/tests/ai_irq_test.c", "sw/common/crt0.S", "sw/ai_model/golden_vectors/ai_sram_init.hex"],
        "dut": ["rtl/ai_accelerator/ai_accelerator.sv", "rtl/soc_top.sv", "rtl/core/cv32e40p/rtl/cv32e40p_int_controller.sv", "rtl/core/cv32e40p/rtl/cv32e40p_cs_registers.sv"],
        "registers": ["AI.DATA_ADDR", "AI.OUT_ADDR", "AI.CTRL", "AI.STATUS", "UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "make soc-ai-irq (part of make test-all); make coverage",
    },
    "timer_irq_test": {
        "title": "Timer count, reload, prescaler, down mode and interrupt (irq 16)",
        "purpose": "Proves the timer's up-count with auto-reload, prescaler, down-count wrap, register read-back and event clear, and that its level interrupt on line 16 is taken and cleared from the ISR.",
        "checks": [
            "Phase 1 (up mode, PRE=0, ARE=9): EVN must reach 2 within the polling timeout; a write of 0xDEADBEEF to the read-only CNT is issued (the value is not checked)",
            "Phase 1 read-back: PRE=0, ARE=9, MOD=1, ENA=1, CLR reads 0, EVC reads 0; after writing EVC, EVN must read 0",
            "Phase 2 (PRE=4, ARE=3): EVN must reach 1 within the timeout",
            "Phase 3 (down mode, ARE=0xFFFFFFFF): EVN must reach 1 within the timeout (wrap from 0)",
            "Phase 4 (interrupt, ARE=19, mie[16] and MIE set): the ISR must run, exactly once, must read a non-zero EVN, and EVN must read 0 after the interrupt",
            'Only if all checks pass does the firmware print "[TIMER] PASS" and "Hello World from BLogic MCU!\\n" (compared by the simulator); make soc-timer also requires result=PASS in result.log',
        ],
        "sources": ["sw/tests/timer_irq_test.c", "sw/common/crt0.S"],
        "dut": ["rtl/peripherals/timer_axil.sv", "rtl/soc_top.sv", "rtl/core/cv32e40p/rtl/cv32e40p_int_controller.sv"],
        "registers": ["TIMER.PRE", "TIMER.ARE", "TIMER.CLR", "TIMER.ENA", "TIMER.MOD", "TIMER.CNT", "TIMER.EVN", "TIMER.EVC", "UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "make soc-timer (part of make test-all); make coverage",
    },
    "uart1_strm_test": {
        "title": "UART_1 stream DMA into AI SRAM",
        "purpose": "Proves the UART_1 byte path and its stream DMA: received bytes are packed into words and written by the stream master into AI SRAM, the status reports the byte count, and an abort stops a transfer without setting DONE. The simulator connects UART_1 TX back to RX.",
        "checks": [
            "UART_1 STP and CPB (50) read back the written values",
            "A raw TDR write of 'Z' must come back on RX: RX_READY within the timeout and RDR equal to 'Z'",
            "STRM_ADDR (0x37000) and STRM_LEN (8) must read back the written values",
            "After STRM_CTRL start and 8 bytes 0xA0..0xA7 sent, STRM_STAT.DONE must set within the timeout, the received count (STRM_STAT bits 31:16) must be 8, BUSY must be 0, and AI SRAM must hold 0xA3A2A1A0 and 0xA7A6A5A4",
            "Abort: with LEN=16, start, 4 bytes, then STRM_CTRL=2, BUSY must drop within the timeout and DONE must stay 0",
            "The irq 18 pulse is not checked by the firmware (it is only reported; the interrupt functional coverage counter observes it)",
            'Only if all checks pass does the firmware print "[STRM] PASS" and "Hello World from BLogic MCU!\\n" (compared by the simulator); make soc-strm also requires result=PASS in result.log',
        ],
        "sources": ["sw/tests/uart1_strm_test.c", "verif/tb/sim_main.cpp"],
        "dut": ["rtl/peripherals/uart_stream_axil.sv", "rtl/peripherals/uart_tx.v", "rtl/peripherals/uart_rx.v", "rtl/ai_accelerator/ai_sram_arbiter.sv", "rtl/core/cv32e40p/rtl/axi_sram_wrapper.sv"],
        "registers": ["UART1.CPB", "UART1.STP", "UART1.TDR", "UART1.CFG", "UART1.RDR", "UART1.STRM_ADDR", "UART1.STRM_LEN", "UART1.STRM_CTRL", "UART1.STRM_STAT", "UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "make soc-strm (part of make test-all); make coverage",
    },
    "ai_sw_reference": {
        "title": "Accelerator versus software inference (speed-up)",
        "purpose": "Runs the same inference on the accelerator and as a bit-exact C implementation on the core, measuring both with mcycle. It proves that the accelerator's convolution output is identical to the software result and that the accelerator is faster.",
        "checks": [
            "Hardware argmax (STATUS bits 7:4) must be 2 ('yes')",
            "Software argmax computed on the core must be 2",
            "All 1000 conv_out words written by the accelerator (0x307A8) must equal the software convolution output (scratch at 0x36000)",
            "Software cycle count must be greater than hardware cycle count",
            'Only if all hold does the firmware print "Hello World from BLogic MCU!\\n" (compared by the simulator, MAX_CYCLES 25000000); make soc-perf also requires result=PASS in result.log',
            "scripts/gen_perf_report.py then parses the PERF lines of uart.log into verif/perf_summary.txt and stops with an error if the log or the lines are missing",
        ],
        "sources": ["sw/tests/ai_sw_reference.c", "sw/ai_model/golden_vectors/quant_params.h", "sw/ai_model/golden_vectors/ai_sram_init.hex", "scripts/gen_perf_report.py"],
        "dut": ["rtl/ai_accelerator/ai_accelerator.sv", "rtl/ai_accelerator/ai_sram_arbiter.sv", "rtl/core/cv32e40p/rtl/cv32e40p_mult.sv", "rtl/core/cv32e40p/rtl/cv32e40p_cs_registers.sv"],
        "registers": ["AI.CTRL", "AI.STATUS", "UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "make soc-perf (part of make test-all)",
    },
    "ai_uart_load_test": {
        "title": "Feature vector loaded over UART_0 and classified",
        "purpose": "Proves the field demo path: a feature vector not used in the fixed 40-sample set is sent by a simulated host over UART_0 in a BLG1 frame, stored in AI SRAM by the firmware and classified by the accelerator with the class predicted by the Python co-simulation.",
        "checks": [
            "sw/ai_model/make_uart_frame.py builds the frame (8 bytes 0xFF, 'BLG1', 4-byte length, 1960 data bytes, 4-byte additive checksum) for sample AI_UART_INDEX (default 784) and writes the expected output line",
            "The simulator stays idle on UART_0 RX until the MCU prints \"[RX] READY - waiting for a vector\", then sends the frame 20000 cycles later at the same CPB (64 by default)",
            "The firmware synchronises on 'BLG1', accepts lengths 1 to 1960 and runs inference only if the received checksum equals the byte sum",
            'UART_0 output must contain "[AI] source=UART  argmax=<N> (<class>)  mem[OUT]=" with the class expected by the co-simulation (golden file compared by the simulator)',
            "sw/ai_model/check_ai_sram.py compares the dumped AI SRAM input region (490 words) with the frame payload; any mismatch fails the target",
            "make ai-uart-load also requires result=PASS in result.log; the initial inference on the built-in vector is printed but not checked",
        ],
        "sources": ["sw/tests/ai_uart_load_test.c", "sw/ai_model/make_uart_frame.py", "sw/ai_model/check_ai_sram.py", "sw/ai_model/run_accuracy_window.py", "verif/tb/sim_main.cpp"],
        "dut": ["rtl/peripherals/uart_axil.sv", "rtl/peripherals/uart_rx.v", "rtl/ai_accelerator/ai_accelerator.sv", "rtl/ai_accelerator/ai_sram_arbiter.sv"],
        "registers": ["UART0.CPB", "UART0.TDR", "UART0.CFG", "UART0.RDR", "AI.DATA_ADDR", "AI.OUT_ADDR", "AI.CTRL", "AI.STATUS"],
        "run": "make ai-uart-load (part of make test-full); make ai-uart-load-field (same run at CPB 434)",
    },
    "isa_compliance_test": {
        "title": "Self-checking RV32IM instruction test",
        "purpose": "Checks 31 results covering RV32I arithmetic, logic, shifts, comparisons, branches, loads and stores, LUI and RV32M multiply and divide, built for rv32imc. Operands declared volatile force the instructions to execute at run time; the constant-only cases may be evaluated by the compiler at -O2.",
        "checks": [
            "Each of the 31 check() calls compares a computed value with the expected value and prints \"FAIL: <name>\" on mismatch",
            'With zero failures the firmware prints ">>> ISA COMPLIANCE PASSED <<<" and "Hello World from BLogic MCU!\\n"; the simulator compares the golden string',
            'make isa-compliance additionally requires result=PASS in result.log and the line ">>> ISA COMPLIANCE PASSED <<<" in uart.log',
        ],
        "sources": ["sw/tests/isa_compliance_test.c"],
        "dut": ["rtl/core/cv32e40p/rtl/cv32e40p_alu.sv", "rtl/core/cv32e40p/rtl/cv32e40p_mult.sv", "rtl/core/cv32e40p/rtl/cv32e40p_alu_div.sv", "rtl/core/cv32e40p/rtl/cv32e40p_decoder.sv", "rtl/core/cv32e40p/rtl/cv32e40p_compressed_decoder.sv", "rtl/core/cv32e40p/rtl/cv32e40p_load_store_unit.sv"],
        "registers": ["UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "make isa-compliance (part of make test-full); make coverage",
    },
    "qspi_fifo_err_test": {
        "title": "QSPI FIFO, flush and status error paths",
        "purpose": "Proves the QSPI master's TX FIFO full and overflow detection, status clearing through CCR bit 31, TX and RX FIFO flush, register read-back, and write-direction, command-only and x4 write transfers. The RX underflow branch is documented as unreachable and not tested.",
        "checks": [
            "TX overflow: after 64 DR writes tx_full is set with no error; a 65th write sets the error field to 0x2",
            "CCR bit 31 clears the error field and DONE",
            "TX flush: tx_empty is 0 before and 1 after FCR TX flush, tx_full is 0 after",
            "RX flush: rx_empty is 1, rx_full is 0 and no error is raised",
            "Read-back: ADR=0x00ABCDEF, CCR=0x08040501 (after the command completes), FCR address-4-byte bit set and cleared",
            "Write direction with address phase, write without address (FCR[4:3]=10), command only (0x06) and x4 write: each must finish with BUSY=0 and DONE=1, and the error field must be 0 where checked",
            'All 25 checks are counted; the golden file requires UART_0 output to contain "[QSPI-ERR] passed=25 failed=0  RESULT: PASS" (compared by the simulator, CPB 64, MAX_CYCLES 3000000)',
        ],
        "sources": ["sw/tests/qspi_fifo_err_test.c"],
        "dut": ["rtl/peripherals/qspi_master_axil.sv"],
        "registers": ["QSPI.FCR", "QSPI.CCR", "QSPI.DR", "QSPI.STA", "QSPI.ADR", "UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "make qspi-err (part of make test-all); make coverage",
    },
    "qspi_modes_test": {
        "title": "QSPI x1/x2/x4 reads and 4-byte addressing against a flash model",
        "purpose": "Proves that the QSPI master reads correct data from a SPI flash model in x1, dual-output and quad-output modes, that 4-byte addressing really drives the upper address byte, and that 3-byte addressing is restored when the mode bit is cleared.",
        "checks": [
            "The flash model is loaded with byte i = i mod 256 (8192 bytes); flash size is 131072 bytes",
            "T1 READ 0x03 x1 at 0x000 must return 0x03020100",
            "T2 DOR 0x3B x2 with 8 dummy cycles at 0x010 must return 0x13121110",
            "T3 QOR 0x6B x4 with 8 dummy cycles at 0x020 must return 0x23222120",
            "FCR bit 2 (4-byte address) must read back as set; T4 READ4B 0x13 at 0x040 must return 0x43424140",
            "T5 READ4B at 0xA5000040 must return 0x25242726, the model's address-derived pattern for addresses above the flash size, which shows the upper address byte is transmitted",
            "T6 after clearing FCR, READ 0x03 at 0x030 must return 0x33323130",
            'The firmware prints "QSPI MODES OK\\n" only if all checks pass; the testbench prints TEST SUCCESS on that line and stops on a line starting with "FAIL" or after a 60 ms timeout; make qspi-modes greps TEST SUCCESS',
        ],
        "sources": ["sw/tests/qspi_modes_test.c", "verif/tb/qspi_modes_tb.sv", "verif/models/spi_flash_model.sv"],
        "dut": ["rtl/peripherals/qspi_master_axil.sv", "rtl/soc_top.sv"],
        "registers": ["QSPI.ADR", "QSPI.CCR", "QSPI.STA", "QSPI.DR", "QSPI.FCR", "UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "make qspi-modes (part of make test-all)",
    },
    "i2c_system_test": {
        "title": "I2C master against an echo slave",
        "purpose": "Proves that the CPU drives the I2C master over the bus against an echo slave model at address 0x42: register clamping and masking, single and four-byte write and read-back, latching of transfer parameters during a transaction, and NACK detection for an absent address.",
        "checks": [
            "NBY clamping: 0 reads 1, 25 reads 4, 3 reads 3",
            "ADR masking: 0xFF reads 0x7F",
            "One byte 0xA5 written and read back with no NACK; RDR must be 0xA5",
            "Four bytes 0x44332211 written and read back with no NACK; RDR must be 0x44332211",
            "Latch: TDR and NBY written during an ongoing 4-byte write do not change it; the read-back must be 0x778899AA",
            "Address 0x13 (no slave) must report NACK",
            'The firmware prints "I2C SYS OK\\n" only with zero failures; the testbench prints TEST SUCCESS on that line and stops on a line starting with "FAIL" or after a 20 ms timeout; make i2c-sys greps TEST SUCCESS',
        ],
        "sources": ["sw/tests/i2c_system_test.c", "verif/tb/i2c_system_tb.sv", "verif/models/i2c_slave_model.sv"],
        "dut": ["rtl/peripherals/i2c_master_axil.sv", "rtl/soc_top.sv"],
        "registers": ["I2C.NBY", "I2C.ADR", "I2C.TDR", "I2C.RDR", "I2C.CFG", "UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "make i2c-sys (part of make test-all)",
    },
    "boot_flash_hello": {
        "title": "Boot from QSPI flash of a C program with read-only data",
        "purpose": "Proves the complete flash boot: the boot ROM bootloader copies the program from flash to the instruction SRAM and the read-only data from flash offset 0x8000 to the data SRAM, then the C program runs and prints a string stored in .rodata.",
        "checks": [
            "make flash-image builds the program and scripts/gen_flash_image.py writes build/flash.hex (program at 0x0, data at 0x8000, AI SRAM image at 0x10000)",
            "The testbench requires 'R' as the first UART_0 character, then sends 'A'",
            "The next 12 characters must equal \"Hello World!\"; if the data region were not copied the program would print NUL bytes and the check fails",
            "The testbench prints TEST SUCCESS (120 ms timeout); make boot-real greps TEST SUCCESS",
        ],
        "sources": ["sw/tests/boot_flash_hello.c", "scripts/gen_flash_image.py", "sw/bootloader/bootloader.S", "sw/bootloader/bootrom.hex", "verif/tb/boot_flow_test_tb.sv", "verif/models/spi_flash_model.sv"],
        "dut": ["rtl/asic/boot_rom.sv", "rtl/peripherals/qspi_master_axil.sv", "rtl/core/cv32e40p/rtl/axi_sram_wrapper.sv", "rtl/peripherals/uart_axil.sv", "rtl/soc_top.sv"],
        "registers": ["UART0.CPB", "UART0.TDR", "UART0.CFG", "UART0.RDR"],
        "run": "make boot-real (part of make test-full)",
    },
    "ai_boot_macro_test": {
        "title": "ASIC top level with SRAM macro models: flash boot and inference",
        "purpose": "Proves on the ASIC top module (asic_top) with the delivered OpenRAM SRAM macro models that the chip boots from flash and runs one bit-exact inference, which exercises all 27 macro instances. Built with CHECK_ARGMAX, it also proves the FC-1 fix (FC1_FIX).",
        "checks": [
            "The testbench requires 'R', sends 'A', then compares the next 12 characters with \"Hello World!\"",
            "The inference input (yes_real) is copied by the bootloader from flash 0x10000 to AI SRAM; DONE must be set within 800000 polls, otherwise \"AI TIMEOUT!!\" is printed",
            "The FNV-1a checksum of the 1000 conv_out words at 0x307A8 must equal 0x9ED98EEF (computed from conv_out_yes_real.hex), otherwise \"CONV CRC BAD\" is printed",
            "With CHECK_ARGMAX: STATUS argmax must be 2 and the low nibble of the result word must be 2, otherwise \"AI ARGMAX BAD\" is printed",
            "The testbench prints TEST SUCCESS (120 ms timeout); make asic-top-sim greps TEST SUCCESS",
        ],
        "sources": ["sw/tests/ai_boot_macro_test.c", "scripts/gen_flash_image.py", "sw/ai_model/golden_vectors/ai_sram_init.hex", "sw/ai_model/golden_vectors/conv_out_yes_real.hex", "verif/tb/asic_top_boot_tb.sv", "verif/models/spi_flash_model.sv"],
        "dut": ["rtl/asic/asic_top.sv", "rtl/asic/sram_macro_bank.sv", "asic/macros/sky130_sram_2kbyte_1rw1r_32x512_8/verilog/sky130_sram_2kbyte_1rw1r_32x512_8.v", "asic/macros/sky130_sram_1kbyte_1rw1r_32x256_8/verilog/sky130_sram_1kbyte_1rw1r_32x256_8.v", "rtl/ai_accelerator/ai_accelerator.sv", "rtl/asic/boot_rom.sv", "rtl/peripherals/qspi_master_axil.sv"],
        "registers": ["UART0.CPB", "UART0.TDR", "UART0.CFG", "UART0.RDR", "AI.DATA_ADDR", "AI.OUT_ADDR", "AI.CTRL", "AI.STATUS"],
        "run": "make asic-top-sim (part of make test-full)",
    },
    "gpio_led_test": {
        "title": "GPIO output register write and read-back",
        "purpose": "Proves that the GPIO output data register stores and returns every one of the 16 output bits, and that the input register can be read.",
        "checks": [
            "Walking one over bits 0 to 15: each value written to ODR must read back unchanged",
            "All on (0x0000FFFF) and all off (0x00000000) must read back unchanged",
            "IDR is read and printed but not checked (the simulator drives the GPIO inputs to 0)",
            'Only if all checks pass does the firmware print ">>> GPIO PASS <<<" and "Hello World from BLogic MCU!\\n" (compared by the simulator)',
        ],
        "sources": ["sw/tests/gpio_led_test.c"],
        "dut": ["rtl/peripherals/gpio_axil.sv"],
        "registers": ["GPIO.ODR", "GPIO.IDR", "UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "make coverage; make sim FW_SRC=sw/tests/gpio_led_test.c",
    },
    "csr_negatif_test": {
        "title": "Negative accesses to unmapped and read-only offsets",
        "purpose": "Proves that accesses inside a peripheral window but to unmapped or read-only offsets fall into the decoder default branches: writes are ignored without side effects and reads return 0, for GPIO, UART_0, UART_1, timer, QSPI and the AI CSRs.",
        "checks": [
            "GPIO: a write to the read-only IDR leaves ODR at 0x1234; offset 0x08 reads 0",
            "UART_0: offset 0x14 reads 0",
            "UART_1: reading the write-only STRM_CTRL (0x1C) returns 0; offset 0x24 reads 0",
            "Timer: a byte read at offset 0x01 returns 0",
            "QSPI: a write to unmapped 0x18 leaves CCR and FCR unchanged; offsets 0x14 and 0x18 read 0",
            "AI CSR: a write to unmapped 0x10 leaves DATA_ADDR at 0x00030000; offset 0x10 reads 0",
            'Only with zero failures does the firmware print "Hello World from BLogic MCU!\\n" (compared by the simulator)',
        ],
        "sources": ["sw/tests/csr_negatif_test.c"],
        "dut": ["rtl/peripherals/gpio_axil.sv", "rtl/peripherals/uart_axil.sv", "rtl/peripherals/uart_stream_axil.sv", "rtl/peripherals/timer_axil.sv", "rtl/peripherals/qspi_master_axil.sv", "rtl/ai_accelerator/ai_accelerator.sv"],
        "registers": ["GPIO.ODR", "GPIO.IDR", "UART1.STRM_CTRL", "TIMER.PRE", "QSPI.CCR", "QSPI.FCR", "AI.DATA_ADDR", "UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "make coverage (built with -DTEST_CPB=64, simulator +CPB=64)",
    },
    "i2c_soc_test": {
        "title": "I2C master at SoC level (no slave, SDA input held low)",
        "purpose": "Proves the I2C master register paths and transfer engine through the CPU and bus in the generic simulator, where the SDA input is not driven and reads 0. Every ACK window therefore sees ACK and every received bit is 0, which makes the results deterministic.",
        "checks": [
            "Reset values: NBY=1, ADR=0, RDR=0, CFG=0",
            "NBY clamping: 0 reads 1, 7 reads 4, 3 reads 3",
            "ADR (0x50) and TDR (0xDEADBEEF) read back",
            "A write to the read-only RDR is ignored (reads 0); unmapped offset 0x14 reads 0",
            "Four-byte write to address 0x2A: TX_DONE within the timeout and no NACK; writing CFG=0 clears all flags",
            "Four-byte read: RX_DONE within the timeout, no NACK and RDR=0",
            "One-byte write: TX_DONE within the timeout",
            'Only with zero failures does the firmware print "Hello World from BLogic MCU!\\n" (compared by the simulator)',
        ],
        "sources": ["sw/tests/i2c_soc_test.c"],
        "dut": ["rtl/peripherals/i2c_master_axil.sv"],
        "registers": ["I2C.NBY", "I2C.ADR", "I2C.RDR", "I2C.TDR", "I2C.CFG", "UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "make coverage (built with -DTEST_CPB=64, simulator +CPB=64)",
    },
    "qspi_rdpath_test": {
        "title": "QSPI master read paths",
        "purpose": "Proves the QSPI master read-direction paths against the simulator's fixed 0xAA responder: multi-byte word packing including 2- and 3-byte tails, dummy cycles, commands without address, address without data, 4-byte addressing, x2 and x4 reads and an x2 write.",
        "checks": [
            "Every command must finish with BUSY=0, DONE=1 and an empty error field",
            "READ 0x03 of 8 bytes: two words 0xAAAAAAAA and RX FIFO empty afterwards",
            "READ of 6 bytes: full word 0xAAAAAAAA and a tail of 0x0000AAAA or 0xAAAA0000; READ of 7 bytes: full word and a tail of 0x00AAAAAA or 0xAAAAAA00",
            "FAST_READ 0x0B with 8 dummy cycles must return 0xAAAAAAAA",
            "RDSR 0x05 with the address phase forced off must return 0x00000000 (sampled before the responder starts)",
            "RES 0xAB without address and with 24 dummy cycles must return 0xAAAAAAAA",
            "SE 0xD8 with the address phase forced on and no data: completion only",
            "READ4 0x13 with 4-byte addressing (ADR 0x01234567) must return 0xAAAAAAAA",
            "DOR 0x3B (x2), QOR 0x6B (x4) and dual page program 0xA2 (x2 write): completion only; the read data is printed but not checked",
            'Only with zero failures does the firmware print "Hello World from BLogic MCU!\\n" (compared by the simulator)',
        ],
        "sources": ["sw/tests/qspi_rdpath_test.c", "verif/tb/sim_main.cpp"],
        "dut": ["rtl/peripherals/qspi_master_axil.sv"],
        "registers": ["QSPI.ADR", "QSPI.FCR", "QSPI.CCR", "QSPI.STA", "QSPI.DR", "UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "make coverage (built with -DTEST_CPB=64, simulator +CPB=64)",
    },
    "ai_sat_test": {
        "title": "AI accelerator requantisation saturation",
        "purpose": "Proves the upper and lower saturation branches of the accelerator's requantisation by writing extreme convolution bias values into AI SRAM, which the accelerator reloads at every start.",
        "checks": [
            "Run 1, all 8 conv biases set to +2^30: DONE within 3000000 polls, and all 1000 conv_out words must be 0x7F7F7F7F",
            "Run 2, all 8 conv biases set to -2^30: DONE within 3000000 polls, and all 1000 conv_out words must be 0x80808080",
            "The argmax of each run is printed for information only",
            'Only with zero failures does the firmware print "Hello World from BLogic MCU!\\n" (compared by the simulator)',
        ],
        "sources": ["sw/tests/ai_sat_test.c", "sw/ai_model/golden_vectors/ai_sram_init.hex"],
        "dut": ["rtl/ai_accelerator/ai_accelerator.sv", "rtl/ai_accelerator/ai_sram_arbiter.sv"],
        "registers": ["AI.DATA_ADDR", "AI.OUT_ADDR", "AI.CTRL", "AI.STATUS", "UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "make coverage (built with -DTEST_CPB=64, simulator +CPB=64)",
    },
    "ai_multi_class_test": {
        "title": "AI accelerator, all four classes",
        "purpose": "Proves that the accelerator classifies one input of each class (silence, unknown, yes, no) correctly in a single run, using four synthetic input vectors placed in AI SRAM by a separate preload image.",
        "checks": [
            "For each scenario the vector is copied from its AI SRAM slot (0x0, 0x5A60, 0x6208, 0x69B0) to the input area, and a sentinel 0xDEADBEEF is written to the result word",
            "DONE must be set within 500000 polls",
            "The result word must no longer be the sentinel",
            "STATUS argmax and the low nibble of the result word must both equal the expected class (0, 1, 2, 3)",
            'Only if all four scenarios pass does the firmware print "Hello World from BLogic MCU!\\n" (compared by the simulator)',
        ],
        "sources": ["sw/tests/ai_multi_class_test.c", "sw/ai_model/generate_ai_sram_init_multi.py", "sw/ai_model/golden_vectors/ai_sram_init_multi.hex"],
        "dut": ["rtl/ai_accelerator/ai_accelerator.sv", "rtl/ai_accelerator/ai_sram_arbiter.sv"],
        "registers": ["AI.STATUS", "AI.DATA_ADDR", "AI.OUT_ADDR", "AI.CTRL", "UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "No make target. make sim preloads the single-scenario ai_sram_init.hex, so ai_sram_init_multi.hex must be used as the AI SRAM preload image instead for this test to pass.",
    },
    "uart_add_test": {
        "title": "UART_0 integer formatting (addition)",
        "purpose": "Prints 584 + 268 = 852 in decimal over UART_0. The self-check compares the sum with the same constant expression, so it cannot fail; the test effectively shows decimal output over UART_0.",
        "checks": [
            "Prints the equation line with the computed sum",
            'Prints "[ADD] PASS" and "Hello World from BLogic MCU!\\n"; the simulator compares the golden string',
        ],
        "sources": ["sw/tests/uart_add_test.c"],
        "dut": ["rtl/peripherals/uart_axil.sv", "rtl/peripherals/uart_tx.v"],
        "registers": ["UART0.CPB", "UART0.TDR", "UART0.CFG"],
        "run": "No dedicated make target; make sim FW_SRC=sw/tests/uart_add_test.c",
    },
    "uart_stp_reg_test": {
        "title": "UART_0 extended stop bits and register read-back",
        "purpose": "Exercises UART_0 transmission with STP codes 2 (+1 bit), 1 (+0.5 bit) and 3 (also +1 bit), including the pending-byte path that queues a TDR write made during the stop-bit extension, and checks register read-back.",
        "checks": [
            "Phase 1 (STP=2): sends 'S' while repeatedly writing 'P' to TDR during the wait, then waits for the queued byte to finish; a hang in either wait loop prevents the golden string",
            "STP must read 1 and CPB 434 after phase 2; RDR and TDR are read but not checked",
            "STP must read 3 after phase 3 and 0 after returning to the default",
            'Only if the read-backs pass does the firmware print "Hello World from BLogic MCU!\\n" (compared by the simulator); the phase messages sent with extended stop bits are logged but not compared',
        ],
        "sources": ["sw/tests/uart_stp_reg_test.c"],
        "dut": ["rtl/peripherals/uart_axil.sv", "rtl/peripherals/uart_tx.v"],
        "registers": ["UART0.CPB", "UART0.STP", "UART0.TDR", "UART0.CFG", "UART0.RDR"],
        "run": "make coverage",
    },
    "demo_main": {
        "title": "Competition demo firmware (UART_1 stream harness path)",
        "purpose": "Demo firmware for the jury harness: it receives 1960-byte feature frames ('BLG1', 16-bit length, payload, CRC16-CCITT) on UART_1, runs the inference with the completion interrupt and prints \"RESULT: <class>\" on UART_0. The simulation targets prove correct classification and frame recovery under truncated, oversized, corrupt and back-to-back frames, and the UART_1 loopback self-test.",
        "checks": [
            "make demo-harness-sim, stream part: 13 scenarios generated by sw/demo/harness_frames.py are sent on UART_1 at CPB 216 (230400 baud) without gaps; the firmware is built with -DDEMO_STREAM_CPB=216",
            "The sequence of RESULT lines on UART_0 (after the boot inference result is dropped) must equal the expected labels from the bit-exact Python software reference; the bad-CRC frame must produce no result (checked by harness_frames.py check)",
            "make demo-harness-sim, loopback part: 'l' is sent on UART_0 with UART_1 in TX-to-RX loopback; uart.log must contain \"loopback frame received\" and at least two \"RESULT: yes\" lines",
            "make demo-harness-sim-dataset: DS_K vectors (default 10) from the generated jury-format set are streamed with a pause at each frame boundary; RESULT lines must equal the manifest's golden labels in order",
            "The simulator's own golden comparison does not apply (the firmware does not print the default golden string) and is ignored by these targets",
        ],
        "sources": ["sw/demo/demo_main.c", "sw/demo/oled_font.h", "sw/demo/harness_frames.py", "sw/demo/team_icd.json", "sw/demo/make_harness_dataset.py", "verif/tb/sim_main.cpp"],
        "dut": ["rtl/peripherals/uart_stream_axil.sv", "rtl/peripherals/uart_axil.sv", "rtl/peripherals/gpio_axil.sv", "rtl/ai_accelerator/ai_accelerator.sv", "rtl/core/cv32e40p/rtl/cv32e40p_int_controller.sv"],
        "registers": ["UART0.CPB", "UART0.TDR", "UART0.CFG", "UART0.RDR", "UART1.CPB", "UART1.CFG", "UART1.RDR", "UART1.TDR", "GPIO.IDR", "GPIO.ODR", "AI.CTRL", "AI.STATUS", "AI.DATA_ADDR", "AI.OUT_ADDR"],
        "run": "make demo-harness-sim; make demo-harness-sim-dataset",
    },
}

TB = {
    "uart-stp": {
        "title": "UART_0 stop-bit lengths",
        "purpose": "Proves that the UART_0 transmitter produces 1, 1.5 and 2 stop bits as selected by the STP register, and that the hardware itself enforces the extended stop time even when software writes the next byte without waiting.",
        "checks": [
            "The testbench writes CPB = 434 (115200 baud at 50 MHz) over AXI-Lite and records the clock cycle of every frame start edge on TXD, masking the data bits inside each frame.",
            "For each STP code 00, 01, 10 and 11 it sends two bytes (0x41, 0x42), polling CFG[2] (TX done) and clearing CFG between them; exactly two new start edges must be seen, otherwise the run stops with $fatal.",
            "Baseline: the start-to-start interval with STP = 00 must be at least 10 bit periods (10 x 432 clocks).",
            "STP = 01 must lengthen the frame by half a bit (216 clocks) and STP = 10 by one full bit (432 clocks), each within 16 clocks.",
            "STP = 11 must give the same interval as STP = 10 within 16 clocks (code 1X decodes as 2 stop bits).",
            "Hardware guarantee: with STP = 2 a second TDR write is issued without polling, timed to fall inside the stop-bit extension; the next start edge must come no earlier than 11 bit periods (4-clock tolerance) and no later than 11 bit periods plus 64 clocks.",
            "The bound functional coverage module (verif/sva/uart_func_cov.sv) counts clocks-per-bit and stop-bit bins, checks that CFG[0] auto-clears after every TX done, reports any violation with $error and prints a coverage summary at the end of simulation.",
            "Pass: the testbench prints TEST SUCCESS, which the make recipe searches for in the log; any $fatal or the 4 ms simulated-time watchdog fails the run.",
        ],
        "sources": ["verif/tb/uart_stp_tb.sv", "verif/sva/uart_func_cov.sv"],
        "dut": ["rtl/peripherals/uart_axil.sv", "rtl/peripherals/uart_tx.v", "rtl/peripherals/uart_rx.v"],
        "log": "obj_dir_uart_stp/uart_stp_run.log",
        "run": "make uart-stp",
    },
    "uart-stream": {
        "title": "UART_1 stream DMA",
        "purpose": "Proves that the UART_1 stream block writes received bytes into memory through its AXI4 master as correct little-endian words, handles partial words, register locking, abort and restart, and still works as an ordinary UART when the DMA is idle.",
        "checks": [
            "The testbench acts as AXI-Lite master for the CSRs and as an AXI4 slave memory (8 KB window at 0x0003_0000, pre-filled with 0xAA); bytes are driven on RXD as 8N1 frames at CPB = 64.",
            "Every AXI4 write from the DUT is checked: single beat (AWLEN = 0), 4-byte size, word-aligned address inside the window and WLAST asserted; any violation stops the run with $fatal.",
            "Scenario A, basic DMA of 16 bytes: BUSY is set and stream_active_o is high after START; after DONE, BUSY and stream_active_o are low, the received count in SSTA[31:16] is 16, an IRQ pulse was seen and the 4 words in memory equal the sent pattern in little-endian order.",
            "Scenario B, partial word of 7 bytes at offset 0x40: the received count is 7, the first word is complete and the last word holds 3 bytes with the untouched top byte still 0xAA (byte-strobe write 0111).",
            "Scenario C: a write to SADR while the transfer is busy is ignored; SADR reads back the original address and the data lands at that address.",
            "Scenario D, ABORT after 3 of 8 bytes: BUSY clears within 1000 status reads, DONE is not set and no IRQ is raised; a new 4-byte transfer then completes correctly and the aborted region still reads 0xAAAAAAAA.",
            "Scenario E, DMA idle: a received byte 0x5A sets CFG[1] and is read from RDR, and a byte written to TDR completes with CFG[2] set.",
            "Pass: the testbench prints TEST SUCCESS after all 5 scenarios; any $fatal, a DONE poll limit of 50000 reads or the 20 ms watchdog fails the run.",
        ],
        "sources": ["verif/tb/uart_stream_tb.sv"],
        "dut": ["rtl/peripherals/uart_stream_axil.sv", "rtl/peripherals/uart_tx.v", "rtl/peripherals/uart_rx.v"],
        "log": "obj_dir_uart_stream/uart_stream_run.log",
        "run": "make uart-stream",
    },
    "boot": {
        "title": "Boot from QSPI flash",
        "purpose": "Proves that the SoC starts from the boot ROM at address 0, copies a program from external QSPI flash into the instruction SRAM and runs it, with no memory preloaded by the simulator.",
        "checks": [
            "The SoC starts at BOOT_ADDR = 0x0000_0000 with the synthesizable boot ROM contents (BOOTROM_CONTENT); the instruction, data and AI SRAM init files are zero, so the program can only arrive through QSPI.",
            "A 128 KB flash model holds an image built by scripts/gen_flash_image.py: the hand-written payload sw/bootloader/flash_helloworld.hex at 0x0 and the AI weights at 0x10000.",
            "The first character received on UART_0 at 115200 baud must be 'R', which shows that the bootloader copied the program and started it.",
            "The testbench then sends 'A' while receiving 12 characters, which must equal \"Hello World!\".",
            "Pass: the testbench prints TEST SUCCESS; a wrong character or the 120 ms simulated-time timeout fails the run.",
        ],
        "sources": ["verif/tb/boot_flow_test_tb.sv", "verif/models/spi_flash_model.sv", "sw/bootloader/bootloader.S", "sw/bootloader/bootrom.hex", "sw/bootloader/flash_helloworld.hex", "scripts/gen_flash_image.py"],
        "dut": ["rtl/soc_top.sv and the full SoC file list soc_files.f", "rtl/asic/boot_rom.sv", "rtl/peripherals/qspi_master_axil.sv", "rtl/core/cv32e40p/rtl/axi_sram_wrapper.sv", "rtl/bus/soc_axi_interconnect.sv", "rtl/peripherals/uart_axil.sv"],
        "log": "obj_dir_boot/boot_run.log",
        "run": "make boot",
    },
    "boot-real": {
        "title": "Boot a C program from flash",
        "purpose": "Proves that a compiled C program boots from flash and that its read-only data region, stored at flash offset 0x8000, is copied by the bootloader into the data SRAM and used at run time.",
        "checks": [
            "make flash-image builds sw/tests/boot_flash_hello.c and packs the program at 0x0, the data region (build/data_mem.hex) at 0x8000 and the AI weights at 0x10000 into build/flash.hex.",
            "The same testbench as make boot runs with this image: the first UART_0 character must be 'R', and after the testbench sends 'A' the next 12 characters must equal \"Hello World!\".",
            "The string is stored in .rodata and read at run time, so if the data region were not copied to the data SRAM the program would print 12 NUL characters and the check would fail.",
            "A negative control is documented in the Makefile comment (make boot-real FLASH_DATA=/dev/null is expected to fail); the recipe does not run it automatically.",
            "Pass: the testbench prints TEST SUCCESS; a wrong string or the 120 ms timeout fails the run.",
        ],
        "sources": ["verif/tb/boot_flow_test_tb.sv", "verif/models/spi_flash_model.sv", "sw/tests/boot_flash_hello.c", "sw/bootloader/bootloader.S", "sw/bootloader/bootrom.hex", "scripts/gen_flash_image.py"],
        "dut": ["rtl/soc_top.sv and the full SoC file list soc_files.f", "rtl/asic/boot_rom.sv", "rtl/peripherals/qspi_master_axil.sv", "rtl/core/cv32e40p/rtl/axi_sram_wrapper.sv"],
        "log": "obj_dir_boot/boot_real_run.log",
        "run": "make boot-real",
    },
    "asic-sram-sim": {
        "title": "Boot with SRAM macro models",
        "purpose": "Proves functional operation of the SoC when its memories are built from the delivered OpenRAM sky130 SRAM macro Verilog models instead of behavioural arrays, using the flash boot flow because it writes and reads all three SRAMs over the bus.",
        "checks": [
            "The SoC is compiled with ASIC_SRAM_MACRO, which switches axi_sram_wrapper and the AI accelerator to the macro bank built from the delivered sky130_sram_2kbyte and sky130_sram_1kbyte models.",
            "There is no $readmemh preload: firmware and AI weights are copied from the QSPI flash model by the boot ROM into the macro-based instruction SRAM and AI SRAM, and the program then runs from the macro contents.",
            "Protocol as in make boot: the first UART_0 character must be 'R', and after the testbench sends 'A' the next 12 characters must equal \"Hello World!\".",
            "The macro models print a line for every access; lines containing Reading or Writing are filtered out of the log, while model warnings stay visible.",
            "Pass: the testbench prints TEST SUCCESS; a wrong string or the 120 ms timeout fails the run.",
        ],
        "sources": ["verif/tb/boot_flow_test_tb.sv", "verif/models/spi_flash_model.sv", "sw/bootloader/flash_helloworld.hex", "sw/bootloader/bootrom.hex", "scripts/gen_flash_image.py"],
        "dut": ["rtl/soc_top.sv and the full SoC file list soc_files.f", "rtl/asic/sram_macro_bank.sv", "asic/macros/sky130_sram_2kbyte_1rw1r_32x512_8/verilog/sky130_sram_2kbyte_1rw1r_32x512_8.v", "asic/macros/sky130_sram_1kbyte_1rw1r_32x256_8/verilog/sky130_sram_1kbyte_1rw1r_32x256_8.v"],
        "log": "obj_dir_boot_macro/macro_boot_run.log",
        "run": "make asic-sram-sim",
    },
    "asic-top-sim": {
        "title": "ASIC top level, boot and inference",
        "purpose": "Proves that the real ASIC top module asic_top, with all SRAM macro models, boots from flash and runs one bit-exact AI inference with the correct class. It is an RTL simulation with behavioural macro models, not a post-layout or SDF-annotated simulation.",
        "checks": [
            "make flash-image builds sw/tests/ai_boot_macro_test.c with CHECK_ARGMAX; the image carries the program, its data region and, at 0x10000, the AI SRAM contents with the recorded \"yes\" input (yes_real).",
            "The DUT is asic_top (not soc_top), compiled with ASIC_SRAM_MACRO and the delivered OpenRAM models, so the port connections of asic_top are exercised and the accelerator's internal input, weight and conv_out macros are used during inference.",
            "The firmware prints 'R', waits for 'A', starts the accelerator and polls STATUS.DONE (a timeout prints \"AI TIMEOUT!!\").",
            "It computes an FNV-1a checksum of the 1000 conv_out words at 0x0003_07A8, which must equal 0x9ED98EEF (golden conv_out_yes_real.hex).",
            "With CHECK_ARGMAX it also requires STATUS.RESULT (argmax) = 2 (\"yes\") and the low 4 bits of the result word in AI SRAM = 2; only then does it print \"Hello World!\", otherwise a different 12-character text.",
            "Model Reading and Writing lines are filtered out of the log.",
            "Pass: the testbench receives 'R' and then exactly \"Hello World!\" and prints TEST SUCCESS; anything else or the 120 ms timeout fails the run.",
        ],
        "sources": ["verif/tb/asic_top_boot_tb.sv", "verif/models/spi_flash_model.sv", "sw/tests/ai_boot_macro_test.c", "sw/bootloader/bootrom.hex", "sw/ai_model/golden_vectors/ai_sram_init.hex", "scripts/gen_flash_image.py"],
        "dut": ["rtl/asic/asic_top.sv", "rtl/soc_top.sv and the full SoC file list soc_files.f", "rtl/ai_accelerator/ai_accelerator.sv", "rtl/asic/sram_macro_bank.sv", "asic/macros/sky130_sram_2kbyte_1rw1r_32x512_8/verilog/sky130_sram_2kbyte_1rw1r_32x512_8.v", "asic/macros/sky130_sram_1kbyte_1rw1r_32x256_8/verilog/sky130_sram_1kbyte_1rw1r_32x256_8.v"],
        "log": "obj_dir_boot_asictop/asictop_run.log",
        "run": "make asic-top-sim",
    },
    "ai": {
        "title": "AI accelerator block test",
        "purpose": "Proves that the AI accelerator alone computes the keyword-spotting network bit-exactly against the reference model for six inputs, checking both the convolution output tensor and the final class.",
        "checks": [
            "The recipe first checks that the reference vectors exist (weights_conv.hex, input_yes.hex, input_yes_real.hex) and stops with instructions if they do not.",
            "The testbench models the AI SRAM as an AXI4 slave and preloads the convolution and fully connected weights and biases; a spot check of the first weight words stops the run with $fatal if loading failed.",
            "Six scenarios are run in order: yes_real and no_real (features of recorded audio) and the synthetic yes, no, unknown and silence inputs.",
            "For each scenario it writes DATA_ADDR and OUT_ADDR, issues START and requires the interrupt within 10 ms; STATUS.DONE must then be 1.",
            "STATUS.RESULT (argmax) must equal the argmax byte of the result word written to memory at 0x0003_5A58, and must equal the argmax of the golden output_<scenario>.hex.",
            "The 1000-word conv_out tensor written at offset 0x07A8 must match the golden conv_out_<scenario>.hex word for word; DONE is then cleared.",
            "If the accuracy batch files exist (acc_batch_inputs.hex, acc_batch_expected.hex), 40 further samples are run and each RTL class must equal the software reference class; mismatches add to the error count.",
            "Pass: with zero errors the testbench prints the step E PASS line that the recipe searches for; if acc_batch_meta.txt exists and the 40th batch line is in the log, run_accuracy_window.py updates the accuracy report from the RTL results.",
        ],
        "sources": ["verif/tb/ai_accel_tb.sv", "sw/ai_model/golden_vectors/", "sw/ai_model/run_accuracy_window.py"],
        "dut": ["rtl/ai_accelerator/ai_accelerator.sv"],
        "log": "obj_dir_ai/ai_run.log",
        "run": "make ai",
    },
    "ai-batch1000": {
        "title": "AI accuracy check, 1000 samples",
        "purpose": "Proves that the accelerator RTL gives the same class as the software (TFLite) reference for 1000 inputs, which bounds any accuracy difference between hardware and software at zero.",
        "checks": [
            "run_accuracy_window.py generates a 1000-sample set and its software reference classes (needs TensorFlow).",
            "The block testbench is rebuilt with BATCH_N = 1000 and a 20 s simulated-time watchdog and runs the 6 standard scenarios followed by the 1000-sample batch; each sample's RTL class (STATUS.RESULT) is compared with the software class.",
            "run_accuracy_window.py reads the per-sample lines from the log and writes the report, which is saved as sw/ai_model/accuracy_report_n1000.txt.",
            "The recipe then restores the 40-sample set and reruns make ai so that accuracy_report.txt is back to 40 samples; this rerun deletes obj_dir_ai, so the 1000-sample log does not survive.",
            "Pass: the saved report states an SW-RTL class match of 1000/1000; otherwise the recipe fails.",
        ],
        "sources": ["verif/tb/ai_accel_tb.sv", "sw/ai_model/run_accuracy_window.py", "sw/ai_model/micro_speech_quantized.tflite", "sw/ai_model/golden_vectors/"],
        "dut": ["rtl/ai_accelerator/ai_accelerator.sv"],
        "log": "sw/ai_model/accuracy_report_n1000.txt",
        "run": "make ai-batch1000",
    },
    "qspi-modes": {
        "title": "QSPI read modes and addressing",
        "purpose": "Proves that the QSPI master reads correct data from a flash model in single, dual and quad data modes and with 4-byte addresses, including an address above 16 MB, and returns to 3-byte addressing.",
        "checks": [
            "The SoC boots at 0x0001_0000 with sw/tests/qspi_modes_test.c preloaded into the instruction SRAM; the flash model holds the byte pattern i mod 256 for 8 KB.",
            "T1: command 0x03 in x1 mode at address 0x000 must read 0x03020100.",
            "T2: dual output read 0x3B (x2, 8 dummy cycles) at 0x010 must read 0x13121110.",
            "T3: quad output read 0x6B (x4, 8 dummy cycles) at 0x020 must read 0x23222120.",
            "FCR[2] (4-byte address mode) is set and must read back as set.",
            "T4: 4-byte read 0x13 at 0x040 must read 0x43424140; T5: 4-byte read at 0xA500_0040 must return the flash model's address hash 0x25242726, which shows the top address byte is really sent.",
            "T6: after FCR[2] is cleared, a 3-byte read at 0x030 must read 0x33323130.",
            "Pass: the firmware prints \"QSPI MODES OK\" on UART_0 and the testbench prints TEST SUCCESS; a line starting with FAIL or the 60 ms timeout fails the run.",
        ],
        "sources": ["verif/tb/qspi_modes_tb.sv", "verif/models/spi_flash_model.sv", "sw/tests/qspi_modes_test.c"],
        "dut": ["rtl/soc_top.sv and the full SoC file list soc_files.f", "rtl/peripherals/qspi_master_axil.sv"],
        "log": "obj_dir_qspi_modes/modes_run.log",
        "run": "make qspi-modes",
    },
    "i2c-sys": {
        "title": "I2C master system test",
        "purpose": "Proves that the CPU can drive the I2C master through the AXI path to write and read an external slave, that register limits and mid-transfer latching behave as specified, and that a missing slave is reported as NACK.",
        "checks": [
            "The SoC boots at 0x0001_0000 with sw/tests/i2c_system_test.c preloaded; an echo slave model at address 0x42 shares an open-drain SDA line with pull-up.",
            "T1: NBY writes of 0, 25 and 3 must read back 1, 4 and 3 (clamping).",
            "T2: ADR write of 0xFF must read back 0x7F (7-bit mask).",
            "T3: a 1-byte write of 0xA5 and a 1-byte read from the slave both complete without NACK, and RDR returns 0xA5.",
            "T4: a 4-byte write of 0x44332211 and a 4-byte read complete without NACK, and RDR returns 0x44332211 packed.",
            "T5: during a 4-byte write of 0x778899AA the firmware overwrites TDR and NBY; the following read must still return 0x778899AA, showing the transfer uses values latched at start.",
            "T6: a write to address 0x13, where no slave answers, must set the NACK flag.",
            "Pass: the firmware prints \"I2C SYS OK\" on UART_0 and the testbench prints TEST SUCCESS; a line starting with FAIL or the 20 ms timeout fails the run.",
        ],
        "sources": ["verif/tb/i2c_system_tb.sv", "verif/models/i2c_slave_model.sv", "sw/tests/i2c_system_test.c"],
        "dut": ["rtl/soc_top.sv and the full SoC file list soc_files.f", "rtl/peripherals/i2c_master_axil.sv"],
        "log": "obj_dir_i2c_sys/i2c_run.log",
        "run": "make i2c-sys",
    },
    "jtag-sim": {
        "title": "JTAG debug, 17 stages",
        "purpose": "Proves the complete JTAG debug path (TAP, DTM, debug module, AXI bridge and CV32E40P debug mode) in the delivered SoC configuration, from basic halt and resume to error and corner cases, by driving the JTAG pins from SystemVerilog.",
        "checks": [
            "The SoC boots at 0x0001_0000 with sw/tests/uart_hello.c preloaded; the JTAG pins are bit-banged in SystemVerilog with TCK at 10 MHz and the system clock at 50 MHz.",
            "Stages 1 to 4: UART_0 prints \"Hello World from BLogic MCU!\"; IDCODE equals 0x0B1061C1; DTMCS reports version 0.13 and abits = 7; after dmactive = 1, dmstatus.version = 2.",
            "Stage 5, halt: haltreq gives allhalted and the core's debug_halted_o = 1.",
            "Stage 6, abstract commands and program buffer: x10 write and read round trip, a store and load to the data SRAM through the program buffer, dpc inside the firmware region and cmderr = 0.",
            "Stage 7, resume: allresumeack and allrunning, debug_running_o = 1, the core PC inside the firmware region and cmderr = 0.",
            "Stage 8, single step and trigger: dcsr.step advances exactly one instruction (new dpc, dcsr.cause = 4); an execute trigger on a loop address halts the core there with dcsr.cause = 2.",
            "Stage 9, ndmreset: the system resets while the debug module stays alive, the core halts at the reset vector (allhavereset, dpc = BOOT_ADDR, dcsr.cause = 3) and after resume the firmware prints its greeting a second time.",
            "Stage 10: DMI busy handling (op = 3, dtmcs.dmistat = 3, dmireset and dmihardreset) and accesses during an abstract command giving cmderr = 1, cleared by write-one-to-clear.",
            "Stages 11 and 12: exceptions in the program buffer give cmderr = 3 without corrupting dpc; unsupported abstract commands give cmderr = 2; a command while the core runs gives cmderr = 4.",
            "Stage 13: system bus access is tied off in the SoC, so sbcs reports sberror = 2, an unsupported size reports sberror = 4, the error clears and nothing hangs.",
            "Stage 14: discovery and WARL behaviour of the debug module registers (dmcontrol, hartinfo, abstractcs, haltsum, nextdm, progbuf0 to 8, data1, tinfo, tselect) and transfer with postexec.",
            "Stage 15: TAP behaviour, including IR capture 0b00101, BYPASS and undefined IR, Pause and Exit2 states, back-to-back scans without Idle, and recovery through Test-Logic-Reset and TRST in the middle of traffic.",
            "Stage 16: the debugger writes code into the instruction SRAM and it executes; with dcsr.ebreakm set, a firmware ebreak enters debug mode with cause 1.",
            "Stage 17: characterises the debug module address region (alias of 0x0004_1000 onto the data SRAM, stale read data at an unmapped offset equal to 0x00100073, a fake halted state caused by normal code, recovery with ndmreset, and a full reset with dmactive = 0); these known limitations are checked against fixed expected values.",
            "Pass: all 17 stages must pass and the testbench prints TEST SUCCESS (17/17), which the recipe searches for in the log.",
        ],
        "sources": ["verif/tb/jtag_smoke_tb.sv", "verif/jtag_cov_waivers.vlt", "sw/tests/uart_hello.c", "sw/bootloader/bootrom.hex"],
        "dut": ["rtl/soc_top.sv and the full SoC file list soc_files.f (JTAG_DEBUG defined)", "rtl/debug/axi_dm_slave.sv", "rtl/debug/vendor/riscv-dbg/src/ (dmi_jtag_tap, dmi_jtag, dmi_cdc, dm_top, dm_csrs, dm_mem, dm_sba)", "rtl/bus/soc_axi_interconnect.sv", "CV32E40P debug logic in rtl/core/cv32e40p/rtl/"],
        "log": "obj_dir_jtag/jtag_run.log",
        "run": "make jtag-sim",
    },
    "jtag-bridge-sim": {
        "title": "Debug module AXI bridge",
        "purpose": "Proves bus behaviours of the AXI bridge in front of the debug module that the SoC master never produces, namely arbitration, held responses, byte strobes and reset during a request, against a real riscv-dbg debug module instance.",
        "checks": [
            "The testbench drives the bridge's instruction and data AXI ports directly and accesses the debug module through DMI; dm_top uses the same parameters as in soc_top.",
            "Stage 1: a data read and an instruction read in the same cycle; the data read must be accepted first, then the instruction read, each with the correct ID.",
            "Stage 2: a data write and an instruction read in the same cycle; the write must be accepted first, its B response must arrive, then the instruction read must complete.",
            "Stage 3: with R_READY held low for 3 cycles, R_VALID must stay high, the debug module request must stay off with the address unchanged, and no new request may be accepted; R_VALID must fall after the handshake.",
            "Stage 4: with B_READY held low for 3 cycles, B_VALID must stay high, the bridge must stay busy and refuse new requests; B_VALID must fall after the handshake.",
            "Stage 5: writes to data0 with strobes 0001, 0011 and 1100 must change only the selected bytes, verified by DMI reads (0xFFFFFF78, 0xFFFFCCDD, 0x9999CCDD).",
            "Stage 6: reset while a read is in flight must clear the pending request and all valid signals; afterwards both ports must read the fixed first debug ROM word 0x0180006F.",
            "The internal resp_pending state must have been active for at least one cycle, otherwise the run fails.",
            "Pass: 6 of 6 stages and resp_pending active; the testbench prints TEST SUCCESS; the 2 ms timeout fails the run.",
        ],
        "sources": ["verif/tb/axi_dm_slave_tb.sv", "rtl/debug/jtag_files.f"],
        "dut": ["rtl/debug/axi_dm_slave.sv", "rtl/debug/vendor/riscv-dbg/src/dm_top.sv and its submodules (from rtl/debug/jtag_files.f)"],
        "log": "obj_dir_jtag_bridge/bridge_run.log",
        "run": "make jtag-bridge-sim",
    },
    "jtag-openocd": {
        "title": "OpenOCD end-to-end demo",
        "purpose": "Proves that the standard OpenOCD debugger can control the simulated SoC over the JTAG remote bitbang protocol: halt, register and memory access, hardware breakpoint, single step, block read and reset.",
        "checks": [
            "The script rebuilds the simulation (make jtag-openocd-build) if it is missing or older than its sources, starts it in the background, waits up to 60 s for TCP port 9999 and runs openocd with blogic_sim.cfg and demo_halt_regs_mem.tcl (900 s limit).",
            "Register a0, after the read-back marker, must be 0x12345678.",
            "A memory read through the program buffer must show cafef00d.",
            "The hardware breakpoint address must equal the first PC reported after the breakpoint is hit.",
            "After reset halt, the first PC must be 0x00010000 (the reset vector).",
            "The PC before and after a single step must both be in 0x0001xxxx and must differ.",
            "An 8-word block read must show b10c0007.",
            "The simulation log must contain the UART greeting at least 3 times (first boot, after reset halt and resume, after reset run).",
            "The demo must reach its done marker, and both openocd and the simulation must exit with code 0.",
            "Pass: all of the above; the script prints VERDICT PASS and exits 0, otherwise VERDICT FAIL and exits 1.",
        ],
        "sources": ["scripts/run_jtag_openocd.sh", "scripts/jtag_sim_stale.sh", "verif/tb/jtag_openocd_tb.sv", "rtl/debug/vendor/riscv-dbg/tb/SimJTAG.sv", "rtl/debug/tb/jtag_dpi.cpp", "rtl/debug/openocd/blogic_sim.cfg", "rtl/debug/openocd/demo_halt_regs_mem.tcl", "sw/tests/uart_hello.c"],
        "dut": ["rtl/soc_top.sv and the full SoC file list soc_files.f (JTAG_DEBUG defined)", "rtl/debug/axi_dm_slave.sv", "rtl/debug/vendor/riscv-dbg/src/"],
        "log": "logs/jtag/openocd.log",
        "run": "make jtag-openocd",
    },
    "jtag-gdb": {
        "title": "gdb source-level debug demo",
        "purpose": "Proves source-level debugging of the simulated SoC with gdb connected through OpenOCD: breakpoint on main, register and memory access, and a clean shutdown.",
        "checks": [
            "The script rebuilds the simulation if it or build/test.elf is missing, stale or out of step with the loaded firmware, starts the simulation (TCP 9999) and OpenOCD (gdb port 3333), and runs gdb-multiarch in batch mode with demo_gdb.gdb on build/test.elf (600 s limit).",
            "gdb must stop with \"Breakpoint 1\" in main, and the first PC printed after it must be in the firmware region 0x0001xxxx.",
            "Register a0 must read back 0x0badcafe.",
            "Memory at 0x00021000 must read back 0x600df00d (written by gdb).",
            "The gdb script must reach its done marker, and gdb.log must not contain \"not supported\", \"Error in sourced command file\" or \"Protocol error with Rcmd\".",
            "gdb, OpenOCD and the simulation must all exit with code 0, and the simulation log must contain the SimJTAG line.",
            "Pass: all of the above; the script prints VERDICT PASS and exits 0, otherwise VERDICT FAIL and exits 1.",
        ],
        "sources": ["scripts/run_jtag_gdb.sh", "scripts/jtag_sim_stale.sh", "verif/tb/jtag_openocd_tb.sv", "rtl/debug/vendor/riscv-dbg/tb/SimJTAG.sv", "rtl/debug/tb/jtag_dpi.cpp", "rtl/debug/openocd/blogic_sim.cfg", "rtl/debug/openocd/demo_gdb.gdb", "sw/tests/uart_hello.c"],
        "dut": ["rtl/soc_top.sv and the full SoC file list soc_files.f (JTAG_DEBUG defined)", "rtl/debug/axi_dm_slave.sv", "rtl/debug/vendor/riscv-dbg/src/"],
        "log": "logs/jtag/gdb.log",
        "run": "make jtag-gdb",
    },
    "jtag-equiv": {
        "title": "JTAG option isolation check",
        "purpose": "Proves that with the JTAG_DEBUG, FC1_FIX and I2C_SDA_SYNC defines left undefined, the RTL is the same as the RTL of the signed ASIC run (commit 73d8dcd), apart from constant folding and a stored list of intended differences.",
        "checks": [
            "The reference versions of rtl/soc_top.sv, rtl/bus/soc_axi_interconnect.sv, rtl/asic/asic_top.sv, rtl/fpga_top.sv and rtl/ai_accelerator/ai_accelerator.sv are taken with git show from commit 73d8dcd (or EQUIV_REF, or the JTAG_MAIN_DIR directory).",
            "Both versions are preprocessed by Verilator with no defines.",
            "The working-tree output is normalised with scripts/jtag_equiv_expected.sed (constant-zero debug wires, reset alias and similar terms that synthesis folds away).",
            "The remaining diff of each file must be identical, line for line, to the stored expected diff in scripts/jtag_equiv_expected_diffs/; a new, missing or changed line fails, and a missing expected-diff file fails.",
            "Pass: the script prints VERDICT PASS and exits 0; otherwise it prints the deviation and exits 1.",
        ],
        "sources": ["scripts/jtag_define_off_equiv.sh", "scripts/jtag_equiv_expected.sed", "scripts/jtag_equiv_expected_diffs/", "scripts/jtag_equiv_known_diffs.txt"],
        "dut": ["rtl/soc_top.sv", "rtl/bus/soc_axi_interconnect.sv", "rtl/asic/asic_top.sv", "rtl/fpga_top.sv", "rtl/ai_accelerator/ai_accelerator.sv"],
        "log": "build/jtag_equiv/ (intermediate files; the verdict is printed to the console)",
        "run": "make jtag-equiv",
    },
    "jtag-gates": {
        "title": "JTAG check bundle",
        "purpose": "Runs every JTAG-related check in one command and reports a summary, so the debug subsystem can be accepted as a whole.",
        "checks": [
            "Runs make jtag-sim, make jtag-bridge-sim, make lint-fpga and make jtag-equiv.",
            "Runs make jtag-openocd only if openocd is installed, and make jtag-gdb only if openocd and gdb-multiarch (or the GDB variable) are installed; otherwise each is reported as SKIP.",
            "Does not stop at the first failure; prints a table with PASS, FAIL or SKIP for each part.",
            "Pass: exit code 0 only if no part failed; skipped parts do not fail the bundle.",
        ],
        "sources": ["Makefile (jtag-gates recipe)", "the sources of jtag-sim, jtag-bridge-sim, lint-fpga, jtag-equiv, jtag-openocd and jtag-gdb"],
        "dut": ["rtl/soc_top.sv with the JTAG debug subsystem", "rtl/debug/axi_dm_slave.sv", "rtl/fpga_top.sv", "rtl/debug/vendor/riscv-dbg/src/"],
        "log": "console summary; each part writes its own log (obj_dir_jtag/jtag_run.log, obj_dir_jtag_bridge/bridge_run.log, build/lint/lint_fpga.log, logs/jtag/)",
        "run": "make jtag-gates",
    },
    "arch-test": {
        "title": "RISC-V architecture tests",
        "purpose": "Proves RV32I, M and C instruction-set compliance of the CV32E40P core inside the SoC by running the official riscv-arch-test programs and comparing their memory signatures with the Spike reference simulator.",
        "checks": [
            "The recipe stops if verif/arch_tests/suite/rv32i_m is missing; the script rebuilds the large-memory SoC model (1 MB instruction SRAM, 64 KB data SRAM) when it is missing or older than its sources, and uses an all-zero boot ROM so that execution traps to 0x10000.",
            "Each test of the selected extensions (default I, M and C) is built for the SoC, run with a 2 million cycle limit, and its signature region and tohost value are read from the data SRAM.",
            "The same test is built with a separate memory layout for Spike, run on Spike, and the reference signature is compared with the DUT signature.",
            "PASS requires a non-zero tohost value (the test reached its end) and a signature equal to Spike's.",
            "KNOWN_DIFF is accepted only when the test name and the checksum of the exact signature diff match an entry in known_diffs.txt (cebreak-01).",
            "A test that did not finish, whose signature differs, or that fails to build is FAIL; without Spike a test is FAIL unless ARCH_ALLOW_NO_SPIKE=1, which turns it into SKIP.",
            "Pass: the script exits with the number of failed tests, so make succeeds only with zero failures; a summary is written to logs/arch_test/summary.txt.",
        ],
        "sources": ["verif/arch_tests/run_arch_test.sh", "verif/arch_tests/suite/", "verif/arch_tests/target/blogic/ (link.ld, link_spike.ld, htif.S)", "verif/arch_tests/known_diffs.txt", "verif/tb/sim_main.cpp", "scripts/elf2hex.py"],
        "dut": ["rtl/soc_top.sv and the full SoC file list soc_files.f, built with enlarged SRAMs", "rtl/core/cv32e40p/rtl/"],
        "log": "logs/arch_test/summary.txt",
        "run": "make arch-test",
    },
    "regression": {
        "title": "SoC regression",
        "purpose": "Proves basic SoC operation at several UART speeds, instruction-level agreement of the core with the Spike simulator, and reading external QSPI flash, with bus protocol checks active.",
        "checks": [
            "Three runs of sw/tests/uart_hello.c with clocks-per-bit 434, 50 and 5208 (115200 baud, 1 Mbps, 9600 baud); each passes when the UART_0 output contains \"Hello World from BLogic MCU!\" (result=PASS in result.log).",
            "Two lockstep runs (sw/tests/minimal_test.c and sw/tests/lockstep_deep.c): the SoC run's retired PC trace is compared by verif/spike/compare_traces.py with Spike's commit log, restricted to 0x10000 to 0x20000 and over the common length; any PC mismatch fails.",
            "One run of sw/tests/qspi_test.c with a flash file starting with 0xAA: the firmware reads the first flash byte and prints the greeting only if it is 0xAA.",
            "For each run, the AXI and AXI-Lite protocol checker reports in the simulation output are counted; any PROTOCOL VIOLATION fails the regression.",
            "Pass: the script exits with the number of failed tests plus protocol violations, so make succeeds only if all 6 tests pass with no violation.",
        ],
        "sources": ["scripts/run_regression.sh", "verif/tb/sim_main.cpp", "verif/spike/compare_traces.py", "verif/sva/axi4_protocol_checker.sv", "verif/sva/axi_lite_protocol_checker.sv", "sw/tests/uart_hello.c", "sw/tests/minimal_test.c", "sw/tests/lockstep_deep.c", "sw/tests/qspi_test.c"],
        "dut": ["rtl/soc_top.sv and the full SoC file list soc_files.f"],
        "log": "logs/regression/<timestamp>/summary.txt (also reachable as logs/latest/)",
        "run": "make regression",
    },
    "coverage": {
        "title": "SoC line and functional coverage",
        "purpose": "Measures RTL line coverage and counter-based functional coverage of the SoC over a fixed set of 15 C tests, and fails if any test fails or the UART auto-clear check is violated.",
        "checks": [
            "The SoC model is rebuilt with Verilator line-coverage instrumentation and coverage waivers.",
            "15 C tests are run (uart_hello, qspi_test, gpio_led_test, ai_micro_speech_test, uart_baud_sweep, ai_irq_test, isa_compliance_test, timer_irq_test, uart_stp_reg_test, uart1_strm_test, qspi_fifo_err_test, i2c_soc_test, csr_negatif_test, qspi_rdpath_test, ai_sat_test); each must pass its own UART output check, otherwise the script stops.",
            "verilator_coverage merges the coverage data and writes annotated sources and the line summary.",
            "Functional coverage bins from verif/sva/*_func_cov.sv are combined over all tests for UART (7 bins), QSPI (7), AI CSR (5) and IRQ (3); UART and IRQ use the true union across tests.",
            "The total count of UART TX-start auto-clear violations must be zero, otherwise the run fails.",
            "The number of uncovered points is listed for each team RTL file, and the JTAG coverage summary from make jtag-cov is appended if present.",
            "The summary is also copied to verif/coverage_summary.txt.",
        ],
        "sources": ["scripts/run_coverage.sh", "verif/tb/sim_main.cpp", "verif/coverage_waivers.vlt", "verif/sva/uart_func_cov.sv", "verif/sva/qspi_func_cov.sv", "verif/sva/irq_func_cov.sv", "verif/sva/ai_func_cov.sv", "sw/tests/ (the 15 tests listed)"],
        "dut": ["rtl/soc_top.sv and the full SoC file list soc_files.f"],
        "log": "logs/coverage/summary.txt",
        "run": "make coverage",
    },
    "soc-perf": {
        "title": "Accelerator versus software speed-up",
        "purpose": "Proves that the AI accelerator and a software implementation of the same network on the CV32E40P give identical results for the recorded \"yes\" input, and measures the speed-up of the hardware.",
        "checks": [
            "The firmware sw/tests/ai_sw_reference.c runs one inference on the accelerator and measures its cycles with mcycle.",
            "It then computes the same inference in software on the core and measures its cycles.",
            "Self-check: the hardware argmax and the software argmax must both be 2 (\"yes\"), all 1000 conv_out words must be equal, and the software must take more cycles than the hardware.",
            "Only then does the firmware print \"Hello World from BLogic MCU!\", which the simulation harness requires for result=PASS (cycle limit 25 million).",
            "scripts/gen_perf_report.py parses the PERF lines from the UART log and writes verif/perf_summary.txt.",
        ],
        "sources": ["sw/tests/ai_sw_reference.c", "verif/tb/sim_main.cpp", "scripts/gen_perf_report.py"],
        "dut": ["rtl/soc_top.sv and the full SoC file list soc_files.f", "rtl/ai_accelerator/ai_accelerator.sv", "rtl/core/cv32e40p/rtl/"],
        "log": "logs/sim/ai_sw_reference/uart.log (report: verif/perf_summary.txt)",
        "run": "make soc-perf",
    },
    "lint": {
        "title": "ASIC top-level lint",
        "purpose": "Proves that the ASIC top level asic_top in the delivered configuration passes Verilator lint without errors.",
        "checks": [
            "The recipe fails if verilator is not on PATH.",
            "Verilator lint runs on asic_top with asic/filelist.f, the same file list as the ASIC flow, including the SYNTHESIS, ASIC_SRAM_MACRO, BOOTROM_CONTENT, JTAG_DEBUG, FC1_FIX and I2C_SDA_SYNC defines.",
            "The MODDUP and PINMISSING warnings are deliberately not suppressed, and the simulation waiver set is not used.",
            "The full output is written to the log and its last 25 lines are printed.",
            "Pass: the log contains no %Error line.",
        ],
        "sources": ["asic/filelist.f"],
        "dut": ["rtl/asic/asic_top.sv and all files in asic/filelist.f"],
        "log": "logs/lint/asic_lint.log",
        "run": "make lint",
    },
    "lint-fpga": {
        "title": "FPGA top-level lint",
        "purpose": "Proves that the FPGA top level fpga_top, with the Xilinx BSCANE2 JTAG TAP used on the board, passes Verilator lint without errors; no simulation target compiles this TAP.",
        "checks": [
            "The recipe fails if verilator is not on PATH.",
            "A temporary file list is made from soc_files.f without dmi_jtag_tap.sv, so the module name is not compiled twice, and dmi_bscane_tap.sv is added instead.",
            "verif/tb/xilinx_prim_stubs.sv provides empty shells of BSCANE2, IBUFDS, BUFG, MMCME2_BASE and STARTUPE2 for lint only.",
            "A count of warnings by type is printed and saved to build/lint/hist_fpga.txt.",
            "Pass: the log contains no %Error line.",
        ],
        "sources": ["soc_files.f", "verif/tb/xilinx_prim_stubs.sv"],
        "dut": ["rtl/fpga_top.sv", "rtl/debug/vendor/riscv-dbg/src/dmi_bscane_tap.sv", "the SoC files from soc_files.f"],
        "log": "build/lint/lint_fpga.log",
        "run": "make lint-fpga",
    },
    "uvm-gpio": {
        "title": "UVM GPIO bench",
        "purpose": "Verifies the GPIO AXI-Lite slave with the shared UVM agent: register write and read-back against a reference model, OKAY responses and AXI-Lite handshake rules.",
        "checks": [
            "Top tb_top drives gpio_axil through the shared AXI-Lite agent; the input port is held at 0xA5A5.",
            "The monitor checks that AWVALID, WVALID, BVALID, ARVALID and RVALID never fall before their handshake and reports violations as UVM_ERROR.",
            "The scoreboard requires an OKAY response on every access and compares every ODR (0x04) read with its model of the last written value (lower 16 bits); IDR reads are checked for response only.",
            "gpio_directed_test: writes 0xCAFE to ODR and reads it back, writes 0xDEAD, reads IDR, then reads ODR again.",
            "gpio_random_test: 50 constrained-random reads and writes to 0x00 and 0x04 with random data; a randomize() failure (for example z3 missing) is a UVM_ERROR.",
            "Pass (in make uvm): the test log reports zero UVM_ERROR and zero UVM_FATAL; the 1 ms simulated-time watchdog raises UVM_FATAL.",
        ],
        "sources": ["verif/uvm/tb_top.sv", "verif/uvm/axi_lite_if.sv", "verif/uvm/axi_lite_uvm_pkg.sv", "verif/uvm-lib/src/uvm_pkg.sv", "Makefile.uvm"],
        "dut": ["rtl/peripherals/gpio_axil.sv"],
        "log": "build/uvm_logs/gpio_directed_test.log and gpio_random_test.log (in make uvm: build/uvm_logs/<test>_s<seed>.log)",
        "run": "make -f Makefile.uvm directed; make -f Makefile.uvm random",
    },
    "uvm-timer": {
        "title": "UVM timer bench",
        "purpose": "Verifies the timer AXI-Lite slave: reset values, register read-back, counting, clear, event accumulation and event clear, plus constrained-random register traffic checked against a reference model.",
        "checks": [
            "Top tb_timer_top drives timer_axil through the shared AXI-Lite agent and protocol monitor.",
            "The scoreboard models PRE, ARE (reset 0xFFFFFFFF), ENA, MOD (reset 1), CLR and EVC (read as 0) and unmapped offsets (read as 0); CNT and EVN are dynamic and checked for response only.",
            "timer_directed_test: reset values of PRE, ARE, ENA and MOD; read-back of PRE, ARE and MOD.",
            "timer_directed_test: with ENA = 0, a CLR pulse leaves CNT at 0; with PRE = 0 and ENA = 1, two CNT reads must show an increasing value.",
            "timer_directed_test: with ARE = 4 and ENA = 1, EVN must become non-zero after about 50 cycles, and an EVC pulse must return EVN to 0.",
            "timer_random_test: 60 constrained-random transactions (writes to 0x00, 0x04, 0x08, 0x0C, 0x10, 0x1C; reads of all 8 registers); each address is checked to lie in its pool, and the write ratio must stay within 25 points of the 60 percent target.",
            "Pass (in make uvm): zero UVM_ERROR and zero UVM_FATAL in the log; the 5 ms watchdog raises UVM_FATAL.",
        ],
        "sources": ["verif/uvm/tb_timer_top.sv", "verif/uvm/axi_lite_if.sv", "verif/uvm/axi_lite_uvm_pkg.sv", "verif/uvm/periph_uvm_pkg.sv", "verif/uvm-lib/src/uvm_pkg.sv", "Makefile.uvm"],
        "dut": ["rtl/peripherals/timer_axil.sv"],
        "log": "build/uvm_logs/timer_directed_test.log and timer_random_test.log (in make uvm: build/uvm_logs/<test>_s<seed>.log)",
        "run": "make -f Makefile.uvm timer_directed; make -f Makefile.uvm timer_random",
    },
    "uvm-uart": {
        "title": "UVM UART_0 bench",
        "purpose": "Verifies the UART_0 AXI-Lite slave: reset values, register read-back, a transmission with automatic clearing of the TX enable flag, flag clearing, and constrained-random register traffic against a reference model.",
        "checks": [
            "Top tb_uart_top drives uart_axil through the shared AXI-Lite agent; RXD is held idle, so there is no receive traffic. This bench compiles uart_tx.v and uart_rx.v from rtl/peripherals/verilog-uart/rtl/.",
            "The scoreboard models CPB (reset 434), STP, TDR and RDR (always 0 without RX) and unmapped offsets (0); CFG is dynamic and checked for response only.",
            "uart_directed_test: reset values CPB = 434, STP = 0, RDR = 0, CFG = 0; read-back of CPB = 50 and STP = 1 and 2.",
            "uart_directed_test: with CPB = 16, CFG[0] = 1 and a TDR write of 0xA5, TDR reads back 0xA5, CFG[2] (TX done) must appear within 300 reads, and CFG[0] must then read 0 (auto-clear).",
            "uart_directed_test: writing CFG = 0 clears all flags, and RDR stays 0.",
            "uart_random_test: 60 constrained-random transactions (writes to CPB, STP, TDR; reads of 0x00 to 0x14) with the same pool and write-ratio checks as the timer bench.",
            "Pass (in make uvm): zero UVM_ERROR and zero UVM_FATAL in the log; the 5 ms watchdog raises UVM_FATAL.",
        ],
        "sources": ["verif/uvm/tb_uart_top.sv", "verif/uvm/axi_lite_if.sv", "verif/uvm/axi_lite_uvm_pkg.sv", "verif/uvm/periph_uvm_pkg.sv", "verif/uvm-lib/src/uvm_pkg.sv", "Makefile.uvm"],
        "dut": ["rtl/peripherals/uart_axil.sv", "rtl/peripherals/verilog-uart/rtl/uart_tx.v", "rtl/peripherals/verilog-uart/rtl/uart_rx.v"],
        "log": "build/uvm_logs/uart_directed_test.log and uart_random_test.log (in make uvm: build/uvm_logs/<test>_s<seed>.log)",
        "run": "make -f Makefile.uvm uart_directed; make -f Makefile.uvm uart_random",
    },
    "uvm-i2c": {
        "title": "UVM I2C bench",
        "purpose": "Verifies the I2C master AXI-Lite slave: reset values, NBY clamping, register read-back, and the NACK path for transmit and receive when no slave is present, plus constrained-random register traffic against a reference model.",
        "checks": [
            "Top tb_i2c_top drives i2c_master_axil through the shared AXI-Lite agent; SDA is an open-drain line with pull-up and no slave, so every address phase is NACKed.",
            "The scoreboard models NBY (clamped to 1 to 4), ADR (7 bits), TDR, RDR (0 until a transfer has been started) and unmapped offsets (0); CFG is dynamic.",
            "i2c_directed_test: reset values NBY = 1, ADR = 0, RDR = 0, CFG = 0; NBY writes 0, 7 and 3 read back 1, 4 and 3; ADR and TDR read back the written values.",
            "i2c_directed_test: a transmit to address 0x2A must set TX done (CFG[1]) within 2000 reads together with the NACK flag (CFG[4]); CFG = 0 then clears all flags.",
            "i2c_directed_test: a receive must set RX done (CFG[3]) with the NACK flag, RDR must stay 0, and CFG = 0 clears the flags.",
            "i2c_random_test: 60 constrained-random transactions (writes to NBY, ADR, TDR only, so no transfer starts; reads of 0x00 to 0x14) with pool and write-ratio checks.",
            "Pass (in make uvm): zero UVM_ERROR and zero UVM_FATAL in the log; the 5 ms watchdog raises UVM_FATAL.",
        ],
        "sources": ["verif/uvm/tb_i2c_top.sv", "verif/uvm/axi_lite_if.sv", "verif/uvm/axi_lite_uvm_pkg.sv", "verif/uvm/periph_uvm_pkg.sv", "verif/uvm-lib/src/uvm_pkg.sv", "Makefile.uvm"],
        "dut": ["rtl/peripherals/i2c_master_axil.sv"],
        "log": "build/uvm_logs/i2c_directed_test.log and i2c_random_test.log (in make uvm: build/uvm_logs/<test>_s<seed>.log)",
        "run": "make -f Makefile.uvm i2c_directed; make -f Makefile.uvm i2c_random",
    },
    "uvm-ai": {
        "title": "UVM AI accelerator bench",
        "purpose": "Verifies both bus interfaces of the AI accelerator with UVM: the AXI-Lite CSR port through the shared agent and the AXI4 master port through a checking memory model, including complete inferences compared with the golden model.",
        "checks": [
            "Top tb_ai_top connects the CSR port to the shared AXI-Lite agent and the AXI4 master port to a memory model of the AI SRAM window (32 KB at 0x0003_0000), preloaded with the weights and the yes_real input; a spot check of the weights stops the run with $fatal if loading failed.",
            "Every AXI4 address phase is checked for single beat, 4-byte size and INCR burst, every write beat for WLAST, and every address for lying inside the window; any violation or out-of-window access is a UVM_ERROR at the end of the test.",
            "On each rising edge of irq_o the 1000 conv_out words are compared with conv_out_yes_real.hex, and the expected class is taken from output_yes_real.hex.",
            "The CSR scoreboard models CTRL (reads 0), DATA_ADDR (reset 0x0003_0000), OUT_ADDR (reset 0x0003_5A58) and unmapped offsets (0); STATUS is dynamic.",
            "ai_directed_test: reset values; DATA_ADDR and OUT_ADDR read-back; writes to unmapped offsets 0x10 and 0x1C have no effect; CLEAR_DONE while idle has no effect; irq_o is low before START.",
            "Each inference: BUSY is set after START, irq_o arrives within 2 million cycles, STATUS shows DONE and not BUSY, STATUS.RESULT equals the golden class, the last AXI4 write goes to OUT_ADDR with the result as data, conv_out has zero differences, exactly 1001 words are written (1000 conv_out plus 1 result), and CLEAR_DONE clears DONE and irq_o.",
            "ai_directed_test runs a first inference with the default result address and a second one with OUT_ADDR = 0x0003_7F00 and a second START while busy; after waiting 1.5 inference times the DONE count must be exactly 2.",
            "ai_random_test: 80 constrained-random CSR accesses visiting all 8 offsets in shuffled order, never writing STATUS and never setting START; CTRL, DATA_ADDR and OUT_ADDR must each be written and STATUS read at least once, no inference may complete, and a full inference afterwards must still be correct.",
            "Pass (in make uvm): zero UVM_ERROR and zero UVM_FATAL in the log; the 60 ms watchdog raises UVM_FATAL.",
        ],
        "sources": ["verif/uvm/tb_ai_top.sv", "verif/uvm/ai_side_if.sv", "verif/uvm/ai_uvm_pkg.sv", "verif/uvm/axi_lite_if.sv", "verif/uvm/axi_lite_uvm_pkg.sv", "verif/uvm/periph_uvm_pkg.sv", "verif/uvm-lib/src/uvm_pkg.sv", "sw/ai_model/golden_vectors/", "Makefile.uvm"],
        "dut": ["rtl/ai_accelerator/ai_accelerator.sv (behavioural memories, ASIC_SRAM_MACRO undefined)"],
        "log": "build/uvm_logs/ai_directed_test.log and ai_random_test.log (in make uvm: build/uvm_logs/<test>_s<seed>.log)",
        "run": "make -f Makefile.uvm ai_directed; make -f Makefile.uvm ai_random",
    },
    "uvm": {
        "title": "UVM regression, all benches",
        "purpose": "Runs the five UVM benches (GPIO, timer, UART_0, I2C and AI accelerator) from a clean build, the directed tests once and the constrained-random tests once per seed, and fails if any run reports a UVM error.",
        "checks": [
            "Makefile.uvm all first checks that the z3 constraint solver is on PATH and that Verilator is version 5.052 or later, then removes old output and builds the five benches, each in its own directory with coverage enabled.",
            "Each directed test runs once and each random test once for every seed in UVM_SEEDS (default 1 2 3), giving 20 runs by default.",
            "A run passes when its log contains \"UVM_ERROR :    0\" and \"UVM_FATAL :    0\"; coverage data is written per run.",
            "Pass: make exits with the number of failed runs, so it succeeds only when all runs pass; a summary line gives the pass and fail counts.",
        ],
        "sources": ["Makefile.uvm", "verif/uvm/", "verif/uvm-lib/src/"],
        "dut": ["rtl/peripherals/gpio_axil.sv", "rtl/peripherals/timer_axil.sv", "rtl/peripherals/uart_axil.sv", "rtl/peripherals/verilog-uart/rtl/uart_tx.v", "rtl/peripherals/verilog-uart/rtl/uart_rx.v", "rtl/peripherals/i2c_master_axil.sv", "rtl/ai_accelerator/ai_accelerator.sv"],
        "log": "build/uvm_logs/<test>_s<seed>.log (coverage: build/uvm_logs/coverage/)",
        "run": "make uvm",
    },
}

TESTS = {**FW, **TB}
